<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>

<head>
<style>

back {
  background-color: #ddd;
  border: none;
  color: black;
  padding-left: 25px;
   padding-right : 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 1px 0px;
  cursor: pointer;
  border-radius: 16px;
  height:30px;
}</style></style>
<title>Potential Vendor Master</title>
<link rel="stylesheet"
	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
	crossorigin="anonymous">
<link
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
	rel="stylesheet"
	integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
	crossorigin="anonymous">
<script
	src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
	integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
	crossorigin="anonymous"></script>
<script
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
	integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
	crossorigin="anonymous"></script>
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<script type="text/javascript">
	$(document)
			.ready(
					function() {
						// INDUSTRIES
						var country_arr1 = new Array("SELECT INDUSTRY",
								"AUTOMATION INDUSTRY", "AUTOMOBILE INDUSTRY",
								"ALLIED ENGINEERING INDUSTRY",
								"CHEMICAL INDUSTRY", "CONSTRUCTION INDUSTRY",
								"ENGINEERING CONSUMABLES",
								"ELECTRICALS,ELECTRONICS INDUSTRY",
								"GENERAL PURPOSE ITEMS", "IT INDUSTRY",
								"PLASTIC AND RUBBER INDUSTRY",
								"PACKAGING INDUSTRY", "PLANT AND MACHINERY",
								"SERVICE INDUSTRY");

						$.each(country_arr1, function(k, item) {
							$('#industry1').append($('<option>', {
								value : k,
								text : item,
							}, '</option>'));
						});

						// CATEGORIES
						var s_a21 = new Array();
						s_a21[0] = "";
						//1. AUTOMATION INDUSTRY
						s_a21[1] = "SELECT CATEGORY|AUTOMATION MACHINES|DENSITY MEASURING INSTRUMENTS|DIGITAL MEASURING INSTRUMENTS|DISTRIBUTED CONTROL SYSTEM (DCS)|ELCTRONIC THROTTLE CONTROLS|FLOW MEASURING EQUIPMENTS|INDUSTRIAL HEATING EQUIPMENTS|INDUSTRIAL PROCESS CONTROL EQUIPMENT|INDUSTRIAL VALVES AND AUTOMATED VALVES|INSTRUMENT CONTROL PANNEL AND ASSEMBLY|LABRATORY AND SCIENTIFIC INSTRUMENTS|LEVEL GAUGES AND MEASURING INSTRUMENTS|MEASURING INSTRUMENTS|ELECTRONIC MACHINES FOR MEDICAL APPLICATION|PRESSURE MEASURING INSTRUMENTS|PRINTED CIRCUIT BOARDS|RECTIFIERS CONTROL PANELS|ROBOTICS AUTOMATION|SCIENTIFIC INSTRUMENT|SPECIAL PURPOSE MACHINE AND ASEMBLY LINE AUTOMATION|SUPERVISORY CONTROL AND DATA ACCUISITION(SCADA)|TEMPERATURE INSTRUMENT|THERMAL GAUGES|VIBRTION MEASURING INSTRUMENTS";
						// 2.AUTOMOBILE INDUSTRY
						s_a21[2] = "SELECT CATEGORY|AUTO AIR CONDITIONING SYSTEM|AUTO BATTERY INDUSTRY|AUTO ELECTRIC PARTS|AUTO ELECTRONIC AND MECHANICAL SECURITY SYSTEM|AUTO ENGINEERING PARTS|AUTO DIE CASTING COMPONENTS|AUTO PART-RUBBER BEEDING|AUTO FABRICATION|AUTO PARTS-FORGING|AUTO PARTS-GAUGES|AUTO PARTS-INJECTION MOULDING PLASTIC AND INTERIORS|AUTO-LIGHTING SYSTEM|AUTO PARTS-RUBBER MATS AND PARTS|AUTO PARTS-SHEET METAL AND PRESS PARTS|AUTO PARTS-TYRES AND TUBES|AUTO PARTS HOSES AND PIPES|AUTO RESEARCH AND DEVELOPMENT|AUTO SEAT ASSEMBLY|AUTOMOBILE INDUSTRY-AGRICULTURE|AUTOMOBILE INDUSTRY-HEAVY VEHICLE|AUTOMOBILE INDUSTRY-FOUR WHEELER|AUTOMOBILE INDUSTRY-TWO WHEELER|AUTO-TELEMATICS,ITS IOT|BATTERY CHARGING STATIONS|FIRE FIGHTING VEHICLES";
						//3.ALLIED ENGINEERING INDUSTRY
						s_a21[3] = "SELECT CATEGORY|AIR COMPRESSOR|INDUSTRIAL STORAGE TANKS|CENTRALIZED LUBRICATION SYSTEM|BIOTECH EQUIPMENT|CNC MACHINE|COATING LINE MACHINERY|DRIP IRRIGATION FILTERS ETC|ENVIRO EQUIPMENTS|FILTRATION EQUIPMENT|FOUNDRIES|FRP PRODUCTS|GAUGES MANUFACTURER|GEAR BOX MANUFACTURER|GENERAL PURPOSE MACHINERY|HVAC SYSTEM AND COOLING MODULES|HYDRAULIC MACHINERY|HYDRAULIC POWER PACKS|I.C.ENGINES|IMPREGATION MACHINE|INDUCTION EQUIPMENT|INDUCTION HARDENING EQUIPMENT|INDUCTION HEATING EQUIPMENTS|INDUSTRIAL BURNERS|INDUSTRIAL CONVEYOR|INDUSTRIAL CRANES AND LIFTING MACHINERY|INDUSTRIAL PIPING|INDUSTRIAL VACCUM PUMPS|INDUSTRIAL VIBRATOR|MACHINERY FOR MAKING RUBBER PRODUCTS|MACHINERY FOR MAKING PLASTIC PRODUCTS|MACHINES FOR AUTOMOBILE INDUSTRIES|MACHINING EQUIPMENTS|GEAR CUTTING MACHINES|MOBILE LIGHTING TOWERS AND ACCESSORIES|NON FERRORS METAL INDUSTRIES|PACKAGING MACHINES|PUMPS|RENEWABLE ENERGY SOLAR WIND|SEWING AND KNITTING MACHINES";
						//4.CHEMICAL INDUSTRY
						s_a21[4] = "SELECT CATEGORY|AGRO FERTILIZERS|AMINO RESINS AND PHENOLIC RESINS|AROMATIC CHEMICALS|BIO CHEMICALS|BOILER CHEMICALS|COLOUR ADDITIVE MASTER BATCHES|CONSTRUCTION CHEMICALS|DRUG INTERMEDIATES|DYES AND PIGMENTS|ELECTROPLASTIC CHEMICALS|FINE CHEMICALS|INORGANIC CHEMICALS|LUBRICANT|ORGANIC CHEMICAL|PESTICIDES,INSECTICIDES,RODENTICIDES,FUNGICIDES,HERBICIDES|RUBBER CHEMICALS|SOLVENT MFG|SPECILATY CHEMICALS|SURFACE ACTIVE AGENT AND EMULSIFIERS|WATER PROOFING CHEMICALS|WATER TREATMENT CHEMICALS";
						//5.CONSTRUCTION INDUSTRY 
						s_a21[5] = "SELECT CATEGORY|BRICKS|SAND AND STONE CRUSHER|ACC BLOCKS|DOORS AND WINDOWS|ALUMINIUM COMPOSITE PANELS AND COLOUR COATING|ASBESTOS CEMENT PRODUCT|BITUMIN AND COALTAR|CEMENT|CERAMIC TILES,MARBLES,STONES|COLD ROLLED FORMED METAL SECTIONS AND COLOUR COATED GALVANISING SHEET|DOOR HANDLES,LATCHES AND LOCKS|FAUCETS|FIRE FIGHTING SYSTEM|PIPES AND FITTINGS|HARDWARE FOR CONSTRUCTION WORK|INTERIOR AND EXTERIOR PAINT,PRIMER|CEMENT AND PLYWOOD BOARDS|PRE ENGINEERING BUILDINGS|READYMIX CONCRETE|REFRACTORY CERAMIC PRODUCTS|ROAD CONSTRUCTION|SANITARY WARES|SCAFFOLDING SUPPLIERS|TMT BAR AND OTHER STEEL ITEMS";
						//6.ENGINEERING CONSUMABLES
						s_a21[6] = "SELECT CATEGORY|GRINDING MATERIAL|ADHESIVE MATERIAL|BEARINGS|VALVES|OIL AND LUBRICANTS|TOOLS AND TACKLES|HARDWARE|WELDING CONSUMABLES|SEALING MATERIAL|PAINTAING MATERIAL|SAFETY MATERIAL|ELECTRICAL CONSUMABLES";
						//7.ELECTRICALS,ELECTRONICS INDUSTRY
						s_a21[7] = "SELECT CATEGORY|CONDUCTOR,INSULATOR AND OHE FITTINGS|ELECTRICAL EQUIPMENTS AND SUPPLIES|LIGHTS AND LIGHTING ACCESSORIES|SOLAR EQUIPMENTS AND PANELS|SWITCH GEAR,RELAY AND CONTACTORS|WIRE,CABLE AND ACCESSORIES|CAPACITORS|ELECTRICAL AND ELECTRONICS MEASURING INSTRUMENTS|ELECTRIC AND ELECTRONIC PANELS|ELECTRIC AC/DC MOTORS|ELECTRIC CIRCUIT BOARD|ELECTRIC POWER DISTRIBUTION TRANSFORMERS";
						//8.GENERAL PUROSE ITEMS
						s_a21[8] = "SELECT CATEGORY|ADVERTISEMENT|FURNITURE|CORPORATE SOUVENIRS AND GIFTS|GROCERIES ANDSERVING ITEMS|HOUSEKEEPING ITEMS|WELFARE AND BRANDING|PROTECTIVE SAFETY EQUIPMENT|STATIONARY";
						//9.IT INDUSTRY
						s_a21[9] = "SELECT CATEGORY|ANIMATION AND GRAPHIC DESIGNING|ARTIFICIAL INTELLIGENCE AND INFORMATION SECURITY|CCTV AND OTHER SECURITY ITEMS AND COMMISSIONING|COMPUTER HARDWARE AND PERIFERRAL DEVICES|CYBER SECURITY|DATA WAREHOUSING AND CLOUD SERVICE PROVIDER|DIGITAL AND SOCIAL MEDIA MARKETING|SMART CARD SOLUTIONS|SOFTWARE INDUSTRY";
						//10.PLASTIC AND RUBBER INDUSTRY
						s_a21[10] = "SELECT CATEGORY|BLOW MOULDED PLASTIC ITEMS|CALENDERED AND MOULDED POLYMER PRODUCTS|CANOPIES AND TENTS|EPS MOULDED PRODUCTS|EXTRUDED RUBBER MATS/SHEETS|INJECTION MOULDED PLASTIC PRODUCTS|MOULDED RUBBER ITEMS|NITRICELLULOSE SHEET/MEMBRANE|NYLON PLASTIC ITEMS|NYLON WIRE AND ROPES|NYLON YARN AND CORD|ENGINEERING PLASTIC ITEMS|PLASTIC WINDOWS AND PROFILES|PLASTIC TUBES AND SLEEVES|PLASTIC PIPES AND FITTINGS|POLYOXY METHYLENE PLASTIC ITEMS|PVC WATER STORAGE TANKS|RUBBER FOAMS|RUBBER SEALS AND GASKETS|RUBBER PART|RUBBER PLATES,SHEETS,STRIPS,RODS,TUBES,PIPES,HOSES|SILICON RUBBER PARTS|SYNTHETIC OR ARTIFICIAL FILAMENT YARN AND TOW|PLASTIC SANITARYWARES|UHMW(ULTRS HIGH MOLECULAR PLASTIC WEIGHT)PLASTIC ITEMS";
						//11.PACKAGING INDUSTRY
						s_a21[11] = "SELECT CATEGORY|CORRUGATED BOX MANUFACTURERS|PLASTIC BAGS,ROLLS,SHEETS(LD,HD,PP,HM)|PP RAFIA BAGS AND ROLLS(WOVEN BAGS AND SACKS)|PLASTIC FILM,MULTILAYER FILM,SHRINK,WRAP FILM|BLOW MOULDING PLASTIC BARRELS,BOTTLES CANS CONTAINERS,TANKS|CRAFT PAPER ROLLS AND BOARDS,PACKING AND WRAPPING PAPER|WOODEN BOXES,CASES,CRATES PLYWOOD BOXES,CABLE DRUMS,PALLETS|PAPER TUBE,CONES,CORES AND CONTAINERS|THERMOCOL PACKING PRODUCTS|COTTON BAGS|ADHESIVE TAPES|LABEL,STICKERS AND SCREEN PRINTING PAPERS|TARRAULINES,PLASTIC,POLY,HDP,CANVAS|PLASTIC STRAPS AND SEALS|PAPER BAGS(PRINTED AND NON-PRINTED)";

						//12.PLANT AND MACHINERY
						s_a21[12] = "SELECT CATEGORY|WATER AND SEWAGE TREATMENT PLANT|AGRICULTURE MACHINERY|ELECTRICAL FURNANCES AND OVENS|FOOD PROCESSING PLANT|HEAVY MATERIAL HANDLING EQUIPMENT|INDUSTRIAL TANKS VESSELES,DRYERS,MIXERS AND AGITATORS|INDUSTRIAL STEAM,OIL,GAS TURBINES AND BOILERS|LIFTS,ESCALATORS AND MOVING WALKWAYS|MACHINES FOR TEXTILE INDUSTRY|MACHINERY FOR DAIRY INDUSTRY|MACHINES FOR OIL REFINERIES|MACHINES FOR PHARMA INDUSTRY|MACHINES FOR PLASTIC INDUSTRY|PACKAGING MACHINES|PLATE AND TUBE HEAT EXCHANGER|POWER GENERATORS SETS|PRESSURE VESSELS|REFIGERATION PLANTS|SHIPPING INDUSTRY|SOLAR PLANT AND EQUIPMENT|SUGAR PLANT MACHINERY";

						//13.SERVICE INDUSTRY
						s_a21[13] = "SELECT CATEGORY|ADVERTISING & DIGITAL MARKETING|ARCHITECTURAL CONSULTANTS|BIO REASEARCH CENTRE|CIVIL CONTRACTORS|CUSTOMS HANDLING AGENTS AND IMPORT WAREHOUSING|CNC MACHINING SERVICES|COURIER SERVICES|ELECTRICAL CONSULTANTS AND CONTRACTORS|ELECTRONIC PCB DESIGING WORK|PLATING AND GALVANISING|FINANCE & INVESTMENT CONSULTANTS|FIRE FIGHTING SERVICES|SURFACE PREPARATION  SERVICES|FOOD & CANTEEN SERVICES|FOUNDRY|LADGING AND BOARDING SERVICES|HOUSE KEEPING CONTRACTORS|HUMAN RESOURCE SERVICES|INSURANCE CONSULTANTS|LEGAL CONSULTANTS|FABRICATION SERVICES|MECHANICAL CONSULTANTS AND CONTRACTORS|MATERIAL TESTING SERVICES|OIL CLEANING AND FILTRATION|DIE,MOULD AND PATTERN MAKING SERVICES|PLUMBING CONTRACTORS|PROCESS CONTROL MANAGEMENT SYSTEM|REPAIR AND MAINTAINENCE SERVICES|SECURITY SERVICES|STORAGE AND WAREHOUSING|TAX CONSULTANTS|TRASPORTATION SERVICES";
						// SUB-CATEGORIES
						var c_a21 = new Array();
						// AUTOMATION INDUSTRY
						c_a21['AUTOMATION MACHINES'] = "SELECT SUB_CATEGORY|FIXED AUTOMATION|PROGRAMMABLE AUTOMATION|FLEXIBALE AUTOMATION|INTEGRATED AUTOMATION";
						c_a21['DENSITY MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|NUCLEAR|CORIOLIS|ULTRASOUND|MICROWAVE|GRAVITIC";
						c_a21['DIGITAL MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|DIGITAL MULTIMETER|DIGITAL VOLTMETER|DIGITAL FREQUENCY METER";
						c_a21['DISTRIBUTED CONTROL SYSTEM (DCS)'] = "";
						c_a21['ELCTRONIC THROTTLE CONTROLS'] = "";
						c_a21['FLOW MEASURING EQUIPMENTS'] = "SELECT SUB_CATEGORY|DIFFERENTIAL PRESSURE METERS|MAGNETIC METERS|MULTIPHASE METERS|ULTRASONIC METERS|VORTEX METERS";
						c_a21['INDUSTRIAL HEATING EQUIPMENTS'] = "SELECT SUB_CATEGORY|FLASK CURE INFRARED REFINERIES|HEATING SYSTEM FOR REFINERIES|OIL HEATING SYSTEM|HOT WATER GENERATOR AND HEAT EXCHANGER|HEAT EXCHANGER|GAS FIRED HOT AIR GENERATOR|ELECTRICAL HEATING SYSTEM|CONVEYOR HEATING SYSTEM";
						c_a21['INDUSTRIAL PROCESS CONTROL EQUIPMENT'] = "SELECT SUB_CATEGORY|INDUSTRIAL AUTOMATION AND CONTROL SYSTEMS(IACS)|HUMAN-MACHINE INTERFACE(HMI)|INTELLIGENT ELECTRONIC DEVICES(IED)|PROGRAMMABLE AUTOMATION CONTROLLERS(PAC)|PROGRAMMABLE LOGIC CONTROLLERS(PLC)|REMOTE TERMINAL UNITS(RTU)|ROSENDHAL INTEGRATED OPERATING SYSTEM(RIO)|VARIABLE FREQUENCY DRIVE(VFD)";
						c_a21['INDUSTRIAL VALVES AND AUTOMATED VALVES'] = "SELECT SUB_CATEGORY|GATE VALVES|GLOBE VALVES|BALL VALVES|BUTTERFLY VALVES|CHECK VALVES|PRESSURE VALVES|DIAPHRAGM VALVES|MOTORISED VALVES";
						c_a21['INSTRUMENT CONTROL PANNEL AND ASSEMBLY'] = "SELECT SUB_CATEGORY|VIRTUAL CONTROL PANEL|REMOTE CONTROL PANEL|PHYSICAL CONTROL PANEL";
						c_a21['LABRATORY AND SCIENTIFIC INSTRUMENTS'] = "";
						c_a21['LEVEL GAUGES AND MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|TRANSPARENT LEVEL GAUGE|REFLEX LEVEL GAUGE|MAGNETIC LEVEL GAUGE|TUBULAR LEVEL GAUGE|BI-COLOR LEVEL GAUGE";
						c_a21['MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|ANGLE LOCATOR|BUBBLE INCLINOMETER|CALIPER|COMPASS|DIGITAL ANGLE GAUGE|LEVEL|LASER LEVEL|MICROMETER";
						c_a21['ELECTRONIC MACHINES FOR MEDICAL APPLICATION'] = "";
						c_a21['PRESSURE MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|BOURDON TUBE PRESSURE GAUGE|DIAPHRAGM PRESSURE GAUGE|CAPSULE PRESSURE GAUGE|ABSOLUTE PRESSURE GAUGE|DIFFERENTIAL PRESSURE GAUGE|BELLOWS PRESSURE GAUGE|MANOMETER PRESSURE GAUGE|PIEZOMETER PRESSURE GAUGE|BEROMETER";
						c_a21['PRINTED CIRCUIT BOARDS'] = "SELECT SUB_CATEGORY|SINGLE-SIDED PCBs|DOUBLE-SIDED PCBs|MULTILAYER PCBs|RIGID PCBs|FLEX PCBs|RIGID-FLEX PCBs";
						c_a21['RECTIFIERS CONTROL PANELS'] = "SELECT SUB_CATEGORY|UNCONTROLLED RECTIFIER|HALF CONTROLLED RECTIFIER|FULL CONTROLLED RECTIFIER";
						c_a21['ROBOTICS AUTOMATION'] = "SELECT SUB_CATEGORY|ROBOTS|ROBOTICS SYSTEM|ROBOTICS PROCESS";
						c_a21['SCIENTIFIC INSTRUMENT'] = "SELECT SUB_CATEGORY|ACCELEROMETER,PHYSICAL,ACCELERATION|AMMETER,ELECTRICAL,AMPERAGE,CURRENT|ANEMOMETER,WIND SPEED|CALIPER,DISTANCE|CALORIMETER,HEAT|DNA SEQUENCER,MOLECULAR BIOLOGY|DYNAMOMETER,TORQUE/FORCE|ELECTROMETER,ELECTRIC CHARGE,POTENTIAL DIFFERENCE";
						c_a21['SPECIAL PURPOSE MACHINE AND ASEMBLY LINE AUTOMATION'] = "";
						c_a21['SUPERVISORY CONTROL AND DATA ACCUISITION(SCADA)'] = "";
						c_a21['TEMPERATURE INSTRUMENT'] = "SELECT SUB_CATEGORY|THERMOCOUPLES|THERMISTORS|RESISTANCE TEMPERATURE DETECTOR (RTD)|PYROMETER|LANGMUIR PROBES(FOR ELECTRON TEMPERATURE OF A PLASMA)|INFRARED THERMOMETER|OTHER THERMOMETERS";
						c_a21['THERMAL GAUGES'] = "SELECT SUB_CATEGORY|THERMOCOUPLE GUAGES|PIRANI GAUGES";
						c_a21['VIBRTION MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|TRANSDUCER|DISPLACEMENT TRANSDUCER|PROXIMITY PROBE|VELOCITY TRANSDUCER|ACCELERATION TRANSDUCERS";

						//AUTOMOBILE INDUSTRY
						c_a21['AUTO AIR CONDITIONING SYSTEM'] = "SELECT SUB_CATEGORY|DUCTED AIR CONDITIONING|SPLIT SYSTEM AIR CONDITIONING|MULTI SPLIT AIR CONDITIONING|CONTROLS";
						c_a21['AUTO BATTERY INDUSTRY'] = "SELECT SUB_CATEGORY|LEAD ACID BATTERY|LITHIUM-ION BATTERY|SLI BATTERY(START,LIGHTING AND IGNITION)|DEEP CYCLE BATTERY|VRLA BATTERY|NICKEL METAL HYDRIDE BATTERY|SILVER CALCIUM BATTERY";
						c_a21['AUTO ELECTRIC PARTS'] = "SELECT SUB_CATEGORY|STARTER MOTOR AND ALTERNATORS|AUTOMOTIVE LIGHTS|WIRING HARNESS|COMPONENTS(COUPLERS AND TERMINALS,RELAY BOXES,JUNCTION BOXES|AUTOMOTIVE METER ASSEMBLIES|AUTOMOTIVE BATTERY CLIPS|AUTO ELECTRICAL SWITCHES,PLUG ADAPTERS,TERMINALS)";
						c_a21['AUTO ELECTRONIC AND MECHANICAL SECURITY SYSTEM'] = "SELECT SUB_CATEGORY|AUTOMOTIVE ELECTRICAL AND ELECTRONIC PARTS|SPEED GOVERNOR|REGULATOR RECTIFIERS|AUTOMOTIVE RELAYS,AUTO FLASHER|AUTO SENSORS|INSTRUMENT CLUSTERS,DISPLAY SYSTEM AND ELECTRONICS";
						c_a21['AUTO ENGINEERING PARTS'] = "SELECT SUB_CATEGORY|HEAT EXCHANGER|EXHAUST SYSTEM|GEAR TRAINS|ENGINE PARTS|AXLE ASSEBLY|EV-COMPONENTS";
						c_a21['AUTO DIE CASTING COMPONENTS'] = "SELECT SUB_CATEGORY|LOW-PRESSURE DIE CASTING|VACUUM DIE CASTING|SQUEEZE DIE CASTING|SEMI-SOLID DIE CASTING";
						c_a21['AUTO PART-RUBBER BEEDING'] = "SELECT SUB_CATEGORY|NATURAL RUBBER|STYRENE BUTADIENE RUBBER(SBR)|NITRILE RUBBER|FLUOROELASTOMERS(FKM)/VITON|ACRYLIC RUBBER|EPDM RUBBER|BUTYL RUBBER|SILICONE RUBBER";
						c_a21['AUTO FABRICATION'] = "SELECT SUB_CATEGORY|FORMING|PUNCHING|SHEARING|STAMPING|WELDING|BUS BODY|CHASIS FEBRICATION|TIPPER";
						c_a21['AUTO PARTS-FORGING'] = "SELECT SUB_CATEGORY|HOT FORGING|COLD FORGING|DROP FORGING PROCESS|PRESS FORGING PROCESS|ROLL FORGING PROCESS|UPSET FORGING PROCESS|ISOTHERMAL FORGING PROCESS";
						c_a21['AUTO PARTS-GAUGES'] = "SELECT SUB_CATEGORY|AIR PRESSURE GAUGES|BLOWER PRESSURE GAUGES|BOOST GAUGES|BRAKE PRESSURE GAUGES|NITROUS PRESSURE GAUGES|VACUUM GAUGES|WATER PRESSURE GAUGES|PRESSURE GAUGES";
						c_a21['AUTO PARTS-INJECTION MOULDING PLASTIC AND INTERIORS'] = "";
						c_a21['AUTO-LIGHTING SYSTEM'] = "SELECT SUB_CATEGORY|AMBIENT LIGHTING|TASK LIGHTING|ACCENT LIGHTING|DECORATIVE LIGHTING";
						c_a21['AUTO PARTS-RUBBER MATS AND PARTS'] = "SELECT SUB_CATEGORY|RUBBER FLOOR MATS|ANTI SLIP MAT|RUBBER STABLE MAT|RUBBER HOLLOW MATS|RUBBER PIN MATS|RING HOLLOW MATS|ANTI FATIGUE RUBBER MAT|SCRAPER MAT";
						c_a21['AUTO PARTS-SHEET METAL AND PRESS PARTS'] = "";
						c_a21['AUTO PARTS-TYRES AND TUBES'] = "SELECT SUB_CATEGORY|TUBETYRES|TUBELESS TYRES";
						c_a21['AUTO PARTS HOSES AND PIPES'] = "SELECT SUB_CATEGORY|FUEL AND OIL HOSES|AIR HOSES|WATER HOSES";
						c_a21['AUTO RESEARCH AND DEVELOPMENT'] = "";
						c_a21['AUTO SEAT ASSEMBLY'] = "";
						c_a21['AUTOMOBILE INDUSTRY-AGRICULTURE'] = "";
						c_a21['AUTOMOBILE INDUSTRY-HEAVY VEHICLE'] = "";
						c_a21['AUTOMOBILE INDUSTRY-FOUR WHEELER'] = "";
						c_a21['AUTOMOBILE INDUSTRY-TWO WHEELER'] = "";
						c_a21['AUTO-TELEMATICS,ITS LOT'] = "SELECT SUB_CATEGORY|AUTO-TELEMATICS,ITS LOT";
						c_a21['BATTERY CHARGING STATIONS'] = "";
						c_a21['FIRE FIGHTING VEHICLES'] = "";

						// ALLIED ENGINEERING INDUSTRY
						c_a21['AIR COMPRESSOR'] = "SELECT SUB_CATEGORY|ROTARY SCREW COMPRESSORS|RECIPROCATING AIR COMPRESSORS|AXIAL COMPRESSORS|CENTRIFUGAL COMPRESSORS|OIL COMPRESSORS";
						c_a21['INDUSTRIAL STORAGE TANKS'] = "SELECT SUB_CATEGORY|STAINLESS STEEL TANKS|MILD STEEL AND RUBBER LINED TANKS|FRP TANKS|PLASTIC TANKS";
						c_a21['CENTRALIZED LUBRICATION SYSTEM'] = "SELECT SUB_CATEGORY|SINGLE-LINE LUBRICATION SYSTEMS|DUAL-LINE LUBRICATION SYSTEMS|MULTI-LINE LUBRICATION SYSTEMS|PROGRESSIVE LUBRICATION SYSTEMS|OIL CIRCULATION LUBRICATION SYSTEMS|OIL AND AIR LUBRICATION SYSTEMS|MINIMAL QUANTITY LUBRICATION SYSTEMS|SOLUTIONS FOR SPECIAL APPLICATIONS";
						c_a21['BIOTECH EQUIPMENT'] = "SELECT SUB_CATEGORY|ELECTROPHORESIS AND BLOTTING|IMAGING AND QUANTITATION|REAL-TIME PCR AND DIGITAL PCR|TRANSFECTION|FLOW CYTOMETRY,CELL SORTING AND CELL COUNTING|PREPARATIVE AND ANALYTICAL AHROMATOGRAPHY|SPECTROPHOOMETRY AND FLUOROMETRY|MULTIPLEX IMMUNOASSAYS";
						c_a21['CNC MACHINE'] = "SELECT SUB_CATEGORY|CNC LATHES AND TURNING MACHINES|CNC MILLING MACHINES|CNC LASER MACHINES|CNC ELECTRICAL DISCHARGE MACHINES(EDM)|CNC PLASMA CUTTING MACHIMNES";
						c_a21['COATING LINE MACHINERY'] = "SELECT SUB_CATEGORY|PLASTIC COATING|METAL COATING|PAPER COATING|RUBBER COATING|CHEMICAL COATING|COLOUR COATING";
						c_a21['DRIP IRRIGATION FILTERS ETC'] = "SELECT SUB_CATEGORY|MICRO DRIP IRRIGATION|TRICKLE DRIP IRRIGATION|SPRINKLER DRIP IRRIGATION";
						c_a21['ENVIRO EQUIPMENTS'] = "";
						c_a21['FILTRATION EQUIPMENT'] = "SELECT SUB_CATEGORY|SEDIMENTATION EQUIPMENT|GRAVITY FILTRATION EQUIPMENT|VACUUM FILTRATION|PRESSURE FILTRATION|THICKENERS|CLARIFIERS|CENTRIFUGAL SEPARATORS";
						c_a21['FOUNDRIES'] = "SELECT SUB_CATEGORY|JOBBING FOUNDRIES|PROTOTYPE CASTINGS|HEAVY ENGINEERING|SPECIALISED AUTOMOTIVE CASTINGS|CASTING FOR MINING SOLUTIONS|CONSTRUCTION EQUIPMENT CASTINGS|PETROCHEMICAL INDUSTRY CASTINGS";
						c_a21['FRP PRODUCTS'] = "SELECT SUB_CATEGORY|FRP SWIMMING POOL|FRP STEAM BATH CHAMBER|PORTABLE SECURITY CABINS|FRP COATING SERVICES|FRP PREFABRICATED OFFICE CABIN|PREFABRICATED FRP CABIN|FRP TOILET BLOCK|FRP MOBILE TOILET";
						c_a21['GAUGES MANUFACTURER'] = "SELECT SUB_CATEGORY|PLUG GAUGE|RING GAUGE|TAPER GAUGE|SNAP GAUGE|FEELER GAUGE|THREAD GAUGE|FORM GAUGE";
						c_a21['GEAR BOX MANUFACTURER'] = "SELECT SUB_CATEGORY|HELICAL GEARBOX|COAXIAL HELICAL INLINE|BEVEL HELICAL GEARBOX|SKEW BEVEL HELICAL GEARBOX|WORM REDUCTION GEARBOXES|PLANETARY GEARBOX";
						c_a21['GENERAL PURPOSE MACHINERY'] = "";
						c_a21['HVAC SYSTEM AND COOLING MODULES'] = "SELECT SUB_CATEGORY|HEATING AND COOLING SPLIT SYSTEMS|HYBRID SPLIT SYSTEM|DUCT FREE(MINI-SPLIT)|PACKAGED HEATING AND AIR CONDITIONING SYSTEM";
						c_a21['HYDRAULIC MACHINERY'] = "";
						c_a21['HYDRAULIC POWER PACKS'] = "";
						c_a21['I.C.ENGINES'] = "SELECT SUB_CATEGORY|SPARK IGNITION GASOLINE ENGINE|COMPRESSION IGNITION DIESEL ENGINE";
						c_a21['IMPREGATION MACHINE'] = "";
						c_a21['INDUCTION EQUIPMENT'] = "";
						c_a21['INDUCTION HARDENING EQUIPMENT'] = "SELECT SUB_CATEGORY|HARDLINE M:MODULAR INDUCTION HARDENING MACHINES|HORIZONTAL INDUCTION HARDENING MACHINES|VERTICAL INDUCTION HARDENING MACHINES|ROTARY TABLE INDUCTION HARDENING MACHINES|CRANKSHAFT INDUCTION HARDENING MACHINES|CUSTOM ENGINEERED INDUCTION HARDENING MACHINES";
						c_a21['INDUCTION HEATING EQUIPMENTS'] = "SELECT SUB_CATEGORY|CORE TYPE OR LOW FREQUENCY INDUCTION|CORELESS TYPE OR HIGH FREQUENCY INDUCTION";
						c_a21['INDUSTRIAL BURNERS'] = "SELECT SUB_CATEGORY|GAS BURNERS.L.P.G/C.N.G/P.R.G/C.B.M|OIL BURNERS.L.D.O/F.O/H.S.D/L.S.H.S|DUAL FUEL BURNERS(GAS AND OIL BURNERS)|MONO BLOCK BURNERS.PRODUCER GAS/BIO GAS/BIO C.N.G/COAL GAS|BURNERS FOR ROTARY KILN.PRODUCTS RANGE.PUSHER FURNACE";
						c_a21['INDUSTRIAL CONVEYOR'] = "SELECT SUB_CATEGORY|AERO-MECHANICAL CONVEYORS|AUTOMOTIVE CONVEYORS|BELT CONVEYOR|BELT-DRIVEN LIVE ROLLER CONVEYORS|BUCKET CONVEYOR|CHAIN CONVEYOR|CHAIN-DRIVEN LIVE ROLLER CONVEYOR|DRAG CONVEYOR";
						c_a21['INDUSTRIAL CRANES AND LIFTING MACHINERY'] = "SELECT SUB_CATEGORY|OVERHEAD CRANES|TRUCK MOUNTED CRANES|TOWER CRANES|GANTRY CRANE|JIB CRANES|ROUGH TERRAIN CRANE|LOADER CRANE";
						c_a21['INDUSTRIAL PIPING'] = "SELECT SUB_CATEGORY|PVC PIPES|PEX PIPES|ABS PIPES|COPPER PIPES|CAST IRON AND GALVANIZED STEEL PIPES|FRP PIPES|RCC HUME PIPES";
						c_a21['INDUSTRIAL VACCUM PUMPS'] = "SELECT SUB_CATEGORY|ROTARY VANE VACUUM PUMPS|DIAPHRAGM VACUUM PUMPS|LIQUID RING VACUUM PUMPS|SCROLL VACUUM PUMPS|TURBOMOLECULAR VACUUM PUMPS:";
						c_a21['INDUSTRIAL VIBRATOR'] = "SELECT SUB_CATEGORY|VIBRATORY MOTOR|ELECTRIC VIBRATOR|VIBRATION SHAKER|PNEUMATIC VIBRATOR|COAL CHUTE VIBRATOR|SYNTRON VIBRATOR|HYDRAULIC CONCRETE VIBRATORS|12 VOLT VIBRATOR";
						c_a21['MACHINERY FOR MAKING RUBBER PRODUCTS'] = "SELECT SUB_CATEGORY|HYDRAULIC PRESSES|COMPRESSION MOLDING PRESSES|DEEP DRAWING PRESSES|TRANSFER AND INJECTION MOLDING PRESSES|VACUUM MOULDING PRESSES|RUBBER MACHINERY|RUBBER BALE CUTTER|DISPERSION KNEADER";
						c_a21['MACHINERY FOR MAKING PLASTIC PRODUCTS'] = "SELECT SUB_CATEGORY|PLASTIC INJECTION MOULDING MACHINE|PLASTIC EXTRUSION MACHINE|PLASTIC BLOW MOULDING MACHINE|THERMOFORMING|ROTATIONAL MOULDING";
						c_a21['MACHINES FOR AUTOMOBILE INDUSTRIES'] = "";
						c_a21['MACHINING EQUIPMENTS'] = "SELECT SUB_CATEGORY|PLANO MILLING MACHINE|HORIZONTAL MILLING AND BORING MACHINE|TURNING AND MILLING MACHINE|DOUBLE COLUMN TYPE MACHINING CENTER|TABLE TYPE HORIZONTAL BORING AND MILLING MACHINE|ROLL GRINDING MACHINE|INTERNAL CYLINDRICAL GRINDING MACHINE";
						c_a21['GEAR CUTTING MACHINES'] = "";
						c_a21['MOBILE LIGHTING TOWERS AND ACCESSORIES'] = "";
						c_a21['NON FERRORS METAL INDUSTRIES'] = "SELECT SUB_CATEGORY|COPPER|ALUMINIUM|LEAD|ZINC|SILVER|GOLD|TITANIUM";
						c_a21['PACKAGING MACHINES'] = "SELECT SUB_CATEGORY|ACCUMULATING AND COLLATING MACHINES|BLISTER PACKS,SKIN PACKS AND VACUUM PACKAGING MACHINES|BOTTLE CAPS EQUIPMENT,OVER-CAPPING,LIDDING,CLOSING,SEAMING AND SEALING MACHINES|BOX,CASE,TRAY AND CARRIER FORMING,PACKING,UNPACKING,CLOSING AND SEALING MACHINES";
						c_a21['PUMPS'] = "SELECT SUB_CATEGORY|POSITIVE DISPLACEMENT PUMPS|CENTRIFUGAL PUMPS|AXIAL FLOW PUMP";
						c_a21['RENEWABLE ENERGY SOLAR WIND'] = "";
						c_a21['SEWING AND KNITTING MACHINES'] = "";

						//CHEMICAL INDUSTRY
						c_a21['AGRO FERTILIZERS'] = "SELECT SUB_CATEGORY|NITROGEN FERTILIZERS|PHOSPHORUS FERTILIZERS|POTASSIUM FERTILIZERS|CALCIUM,MAGNESIUM AND SULPHUR FERTILIZERS|MICRONUTRIENT FERTILIZERS";
						c_a21['AMINO RESINS AND PHENOLIC RESINS'] = "SELECT SUB_CATEGORY|BUTANOL|FLAME RETARDANT|MELAMINE-FORMALDEHYDE RESIN|MONOMERS|PHENOLIC RESIN|POLYESTER RESIN|RESIN|UREA-FORMALDEHYDE RESIN";
						c_a21['AROMATIC CHEMICALS'] = "SELECT SUB_CATEGORY|HISTIDINE|PHENYLALANINE|TRYPTOPHAN|TYROSINE|BENZENE,TOLUENE AND THE XYLENES";
						c_a21['BIO CHEMICALS'] = "SELECT SUB_CATEGORY|CARBOHYDRATES|FATS AND OILS";
						c_a21['BOILER CHEMICALS'] = "SELECT SUB_CATEGORY|SODIUM HYDROXIDE|POTASSIUM HYDROXIDE|BOILER WATER TREATMENT CHEMICAL|HYDRAZINE HYDRATE";
						c_a21['COLOUR ADDITIVE MASTER BATCHES'] = "SELECT SUB_CATEGORY|WHITE MASTERBATCH|BLACK MASTERBATCH|FILLER MASTERBATCH|MODIFIER COMPOUNDS|UV MASTERBATCH|COLOR MASTERBATCH|ADDITIVE MASTERBATCH";
						c_a21['CONSTRUCTION CHEMICALS'] = "SELECT SUB_CATEGORY|CONCRETE ADMIXTURES|CONCRETE CURING COMPOUND|POLYMER BONDING AGENTS|PROTECTIVE AND DECORATIVE AGENTS|WATER REPELLENTS|ADHESIVES|SEALANTS AND CAULKS|EPOXY GROUTS";
						c_a21['DRUG INTERMEDIATES'] = "";
						c_a21['DYES AND PIGMENTS'] = "SELECT SUB_CATEGORY|BASIC DYE|REACTIVE DYE|SULFUR DYE|MORDANT DYE";
						c_a21['ELECTROPLASTIC CHEMICALS'] = "SELECT SUB_CATEGORY|POTASSIUM GOLD CYANIDE|GOLD PLATING CHEMICAL|COPPER CYANIDE|COBALT SULFATE|ZINC PLATING CHEMICAL|PALLADIUM CHLORIDE|SODIUM HYPOPHOSPHITE|ZINC BRIGHTENER";
						c_a21['FINE CHEMICALS'] = "SELECT SUB_CATEGORY|ACTIVE PHARMACEUTICAL INGREDIENTS(API)|PEPTIDES|PRITEINS|STEROIDS|ALKALOIDS|BIOCIDES";
						c_a21['INORGANIC CHEMICALS'] = "";
						c_a21['LUBRICANT'] = "SELECT SUB_CATEGORY|OIL|GREASE|PENETRATING LUBRICANTS|DRY LUBRICANTS|SILICONS";
						c_a21['ORGANIC CHEMICAL'] = "SELECT SUB_CATEGORY|ETHYLENE|PROPYLENE|C4 FRACTION|BENZENE|METHANE";
						c_a21['PESTICIDES,INSECTICIDES,RODENTICIDES,FUNGICIDES,HERBICIDES'] = "";
						c_a21['RUBBER CHEMICALS'] = "SELECT SUB_CATEGORY|ANTIDEGRADANTS/ANTIOXIDANTS|PRE VULCANIZATION INHIBITOR|POST VULCANIZATION STABILIZER";
						c_a21['SOLVENT MFG'] = "SELECT SUB_CATEGORY|ORGANIC SOLVENT|INORGANIC SOLVENT";
						c_a21['SPECILATY CHEMICALS'] = "";
						c_a21['SURFACE ACTIVE AGENT AND EMULSIFIERS'] = "SELECT SUB_CATEGORY|ANIONIC SURFACTANTS|CATIONIC SURFACTANTS|AMPHOTERIC SURFACTANTS|NON-IONIC SURFACTANTS|POLYMERS(SPANS AND TWEENS)|SODIUM LAURYL SULFATE|SODIUM DIOCTYL SULFOSUCCINATE|TRAGACANTH";
						c_a21['WATER PROOFING CHEMICALS'] = "SELECT SUB_CATEGORY|GROUT AND EPOXY|POLYURETHANE|POLYUREA|BITUMINOUS|POLY ACRYLIC|VINYL ESTER RESIN";
						c_a21['WATER TREATMENT CHEMICALS'] = "SELECT SUB_CATEGORY|CHLORINE|CHLORAMINE|CHLORINE DIOXIDE|CALCIUM CARBONATE|TCCA";

						//CONSTRUCTION INDUSTRY

						c_a21['BRICKS'] = "SELECT SUB_CATEGORY|RED BRICK|FLY ASH BRICKS";
						c_a21['SAND AND STONE CRUSHER'] = "SELECT SUB_CATEGORY|GYRATORY CRUSHER|JAW CRUSHER|HORIZONTAL IMPACT CRUSHER|CONE CRUSHER|RIVER SAND";
						c_a21['ACC BLOCKS'] = "SELECT SUB_CATEGORY|100 MM ACC BLOCKS|CONCRETE LILGHTWEIGHT ACC BLOLOCK|CONCRERTE ACC BLOCK|ECO FRIENDLY ACC BLOCKS";
						c_a21['DOORS AND WINDOWS'] = "SELECT SUB_CATEGORY|ALUMINIUM|PVC|WOODEN|ENTRANCE DOOR MANUAL AND MOTORISED";
						c_a21['ALUMINIUM COMPOSITE PANELS AND COLOUR COATING'] = "SELECT SUB_CATEGORY|PROTECTION FILM|PVDF/POLYESTER RESIN BASED COATING|PRIMER COATING|ALUMINIUM COIL|ADHESIVE FILM(POLYOLEFIN)|POLYETHYLENE CORE(LDPE)";
						c_a21['ASBESTOS CEMENT PRODUCT'] = "SELECT SUB_CATEGORY|WALL AND ROOF SHEET(CORRUGATED AND FLAT)|ROOF TILES|RAINWATER GOODS|SEWERAGE PIPE|PRESSURE PIPE";
						c_a21['BITUMIN AND COALTAR'] = "";
						c_a21['CEMENT'] = "SELECT SUB_CATEGORY|ORDINARY PORTLAND CEMENT(OPC)|PORTLAND POZZOLANA CEMENT(PPC)|RAPID HARDENING CEMENT|LOW HEAT CEMENT|SULFATES RESISTING CEMENT|QUICK SETTING CEMENT|BLAST FURNACE SLAG CEMENT";
						c_a21['CERAMIC TILES,MARBLES,STONES'] = "SELECT SUB_CATEGORY|PORCELAIN TILES|MARBLE TILES|MOSAIC TILE|SPC(STONE POLYMER COMPOSITE)|GRANITE TILE|NATURAL STONE TILES";
						c_a21['COLD ROLLED FORMED METAL SECTIONS AND COLOUR COATED GALVANISING SHEET'] = "";
						c_a21['DOOR HANDLES,LATCHES AND LOCKS'] = "SELECT SUB_CATEGORY|STAINLESS STEEL|BRASS|ALUMINIUM|IRON";
						c_a21['FAUCETS'] = "SELECT SUB_CATEGORY|PLASTIC FAUCETS|HARDCHROME PLATED|STAINLESS STEEL|BRASS";
						c_a21['FIRE FIGHTING SYSTEM'] = "SELECT SUB_CATEGORY|WET FIRE SPRINKLER SYSTEMS|DRY PIPE SYSTEMS|SPECIAL HAZARD FIRE PROTECTION SYSTEMS|DRY CHEMICAL FIRE SUPPRESSION SYSTEM|GASEOUS FIRE SUPPRESSION SYSTEMS|FOAM FIRE SUPRESSION SYSTEMS";
						c_a21['PIPES AND FITTINGS'] = "SELECT SUB_CATEGORY|METAL PIPES AND FITTING|PLASTIC PIPES AND FITTING|GAS PIPES AND FITTING|RCC HUME PIPE AND FITTING";
						c_a21['HARDWARE FOR CONSTRUCTION WORK'] = "";
						c_a21['INTERIOR AND EXTERIOR PAINT,PRIMER'] = "SELECT SUB_CATEGORY|OIL-BASED|LATEX-BASED|SHELLAC PRIMER|CEMENT BASED|PLASTIC BASED";
						c_a21['CEMENT AND PLYWOOD BOARDS'] = "";
						c_a21['PRE ENGINEERING BUILDINGS'] = "SELECT SUB_CATEGORY|REINFORCED CEMENT CONCRETE BUILDINGS|STEEL BUILDINGS|TIMBER BUILDINGS|CONVENTIONAL STEEL BUILDINGS|STEEL SECTIONS";
						c_a21['READYMIX CONCRETE'] = "SELECT SUB_CATEGORY|SHRINK MIXED CONCRETE|TRANSIT MIXED CONCRETE|CENTRAL MIXED CONCRETE";
						c_a21['REFRACTORY CERAMIC PRODUCTS'] = "SELECT SUB_CATEGORY|TECHNICAL CERAMICS|THERMAL CERAMICS|HIGH TEMPERATURE CERAMICS(HTCs)|ULTRA-HIGH TEMPERATURE CERAMICS(UHTCs)";
						c_a21['ROAD CONSTRUCTION'] = "SELECT SUB_CATEGORY|WHITETOPPING ROADS|POLYMERE FIBER REINFORCED CONCRETE ROADS|BITUMINOUS ROADS|COMPOSITE PAVEMENT ROAD|GRAVEL ROAD";
						c_a21['SANITARY WARES'] = "SELECT SUB_CATEGORY|URINALS|TOILET SEATS|WATER CLOSET|WASHBASIN|BATHTUB|BIDET|TANKS";
						c_a21['SCAFFOLDING SUPPLIERS'] = "SELECT SUB_CATEGORY|SINGLE SCAFFOLDING|DOUBLE SCAFFOLDING|CANTILEVER SCAFFOLDING|SUSPENDED SCAFFOLDING|TRESTLE SCAFFOLDING|STEEL SCAFFOLDING|PATENTED SCAFFOLDING|WOODEN AND BAMBOO SCAFFOLDING|";
						c_a21['TMT BAR AND OTHER STEEL ITEMS'] = "";

						//6.ENGINEERING CONSUMABLES

						//7.ELECTRICALS,ELECTRONICS INDUSTRY
						c_a21['CONDUCTOR,INSULATOR AND OHE FITTINGS'] = "SELECT SUB_CATEGORY|CONDUCTORS|INSULATORS|OHE FITTING|TRANSMISSION LINE TOOLS";
						c_a21['ELECTRICAL EQUIPMENTS AND SUPPLIES'] = "SELECT SUB_CATEGORY|APPLIANCES AND UTILITIES|BATTERIES,BATTERY CHARGERS AND UPS|ELECTRIC POLES AND ACCESSORIES|ELECTRICAL EARTHING MATERIALS";
						c_a21['LIGHTS AND LIGHTING ACCESSORIES'] = "SELECT SUB_CATEGORY|LED PARTS AND LIGHTING ACCESSORIES|LUMINAIRES|PLUG AND SOCKETS";
						c_a21['SOLAR EQUIPMENTS AND PANELS'] = "SELECT SUB_CATEGORY|SOLAR ACCESSORIES|SOLAR CELL|SOLAR EQUIPMENT|SOLAR LIGHTS";
						c_a21['SWITCH GEAR,RELAY AND CONTACTORS'] = "SELECT SUB_CATEGORY|CIRCUIT BRAKERS|CONTRACTOR|ELECTROMECHANICAL RELAYS|ELECTRONIC RELAYS";
						c_a21['WIRE,CABLE AND ACCESSORIES'] = "SELECT SUB_CATEGORY|CABLE AND WIRE MANAGEMANT|CABLE ACCESSORIES|CABLE MACHINERY AND PARTS|CABLE|CABLE JOINTING KITS";
						c_a21['CAPACITORS'] = "SELECT SUB_CATEGORY|FILM CAPACITORS|POWER FILM CAPACITORS|ELECTROLYTIC CAPACITORS|CERAMIC CAPACITORS|PAPER CAPACITORS";
						c_a21['ELECTRICAL AND ELECTRONICS MEASURING INSTRUMENTS'] = "SELECT SUB_CATEGORY|VOLTMETER|AMMETER|WATTMETER|OHMETER|LCR METER|MULTIMETER|FLUX METER|OSCILLOSCOPE";
						c_a21['ELECTRIC AND ELECTRONIC PANELS'] = "SELECT SUB_CATEGORY|APFC PANEL(AUTOMATIC POWER FACTOR CONTROL)|DG PANEL|POWER CONTROL CENTER(PCC PANEL)|MOTOR CONTROL CENTER(MCC PANEL)|AUTOMATION PANEL(SCADA PLC PANEL)";
						c_a21['ELECTRIC AC/DC MOTORS'] = "";
						c_a21['ELECTRIC CIRCUIT BOARD'] = "SELECT SUB_CATEGORY|SINGLE-SIDED PCBs|DOUBLE-SIDED PCBs|M ULTILAYER PCBs|RIGID PCBs|FLEX PCBs|RIGID-FLEX PCBs";
						c_a21['ELECTRIC POWER DISTRIBUTION TRANSFORMERS'] = "";

						//8.GENERAL PURPOSE ITEMS
						c_a21['ADVERTISEMENT'] = "SELECT SUB_CATEGORY|PRINT MEDIA|DIGITAL MEDIA|AUDIOVISUAL";
						c_a21['FURNITURE'] = "SELECT SUB_CATEGORY|STEEL FURNITURE|WOODEN FURNITURE|CANTEEN FURNITURE AND ACCESSORIES|GLASS ITEMS";
						c_a21['CORPORATE SOUVENIRS AND GIFTS'] = "";
						c_a21['GROCERIES ANDSERVING ITEMS'] = "SELECT SUB_CATEGORY|FOODGRAINS|FRUITS AND VEGETABLES|BEVERAGES AND DRINKING WATER|PACKAGE FOODS|PAPER CUPS,SAUCERS,PLATE AND OTHER SIMILER PRODUCTS";
						c_a21['HOUSEKEEPING ITEMS'] = "SELECT SUB_CATEGORY|CLEANING ITEMS|CLEANING CHEMICALS";
						c_a21['WELFARE AND BRANDING'] = "SELECT SUB_CATEGORY|INDUSTRIAL UNIFORMS|PROMOTIONAL CLOTHING|MISLLENIOUS PROMOTIONAL ITEMS";
						c_a21['PROTECTIVE SAFETY EQUIPMENT'] = "";
						c_a21['STATIONARY'] = "SELECT SUB_CATEGORY|PRINTED STATIONARY|OFFICE STATIONARY|COMPUTER STATIONARY";

						//9.IT INDUSTRY

						c_a21['ANIMATION AND GRAPHIC DESIGNING'] = "SELECT SUB_CATEGORY|MOTION AND ROTOSCOPE ANIMATION|INDUSTRIAL ANIMATION|2D/3D ANIMATION";
						c_a21['ARTIFICIAL INTELLIGENCE AND INFORMATION SECURITY'] = "SELECT SUB_CATEGORY|ARTIFICIAL NARROW INTELLIGENCE(ANI),AGI,ASI|REACTIVE MACHINE,LIMITED MEMORY,THEORY OFMIND AI";
						c_a21['CCTV AND OTHER SECURITY ITEMS AND COMMISSIONING'] = "SELECT SUB_CATEGORY|INDUSTRIAL APPLICATION|HOUSING APPLICATION|ROAD SAFETY AND HIGHWAY";
						c_a21['COMPUTER HARDWARE AND PERIFERRAL DEVICES'] = "SELECT SUB_CATEGORY|WIRELESS COMMUNICATION DEVICES AND WIFI DEVICES PANIC BUTTON ASSEMBLY|TRANSFER SWITCH AND TELECOMMUNICATION CABINET|DESKTOP,LAPTOP|PRINTER AND SCANNER|ROUTERS|EXTERNAL MEMORY";
						c_a21['CYBER SECURITY'] = "SELECT SUB_CATEGORY|CLOUD SECURITY|MOBILE SECURITY|IOT SECURITY|APPLICATION SECURITY";
						c_a21['DATA WAREHOUSING AND CLOUD SERVICE PROVIDER'] = "";
						c_a21['DIGITAL AND SOCIAL MEDIA MARKETING'] = "SELECT SUB_CATEGORY|SEARCH ENGINE OPTIMIZATION|SOCIAL MEDIA MARKETING/MOBILE/EMAIL/EMAILMARKETING|CONTENT MARKETING|MARKETING ANALYTICS";
						c_a21['SMART CARD SOLUTIONS'] = "SELECT SUB_CATEGORY|CONTACT SMART CARDS|CONTACTLESS SMART CARDS|MEMORY SMART CARDS";
						c_a21['SOFTWARE INDUSTRY'] = "SELECT SUB_CATEGORY|PROGRAMMING SERVICES|SYSTEM SERVICES|OPEN SOURCE|SAAS|AI|WEBSITE AND MOBILE APP";

						//10.PLASTIC AND RUBBER INDUSTRY
						c_a21['BLOW MOULDED PLASTIC ITEMS'] = "SELECT SUB_CATEGORY|CONSUMER PRODUCTS|AUTOMOBILE PRODUCTS|FURNITURE PRODUCTS|INDUSTRIAL PRODUCTS|DRUMS CONTAINERS";

						//11.PACKING INDUSTRY

						c_a21['CORRUGATED BOX MANUFACTURERS'] = "SELECT SUB_CATEGORY|3/5/7 PLY CORRUGATED BOX|PRINTED CORRUGATED BOX|HEAVY DUTY INDUSTRIAL CORRUGATED BOX |LAMINATED CORRUGATED BOX|HONEY COMB BOX";
						c_a21['PLASTIC BAGS,ROLLS,SHEETS(LD,HD,PP,HM)'] = "SELECT SUB_CATEGORY|PLAIN PLASTIC BAGS, ROLLS, SHEETS (LD, HD, PP, HM)|AIR BUBBLE BAGS, ROLLS , SHEETS (LD)|STRETCH WRAPPING FILM|LAMINATED ROLLS & POUCHES|AIR  BAGS";
						c_a21['PP RAFIA BAGS AND ROLLS(WOVEN BAGS AND SACKS)'] = "SELECT SUB_CATEGORY|PP RAFIA BAGS AND ROLLS(WOVEN BAGS AND SACKS)|LAMINATED PAPER BAG|FIBC BAGS ( JAMBO BAGS)|NON WOVEN FABRIC|NON WOVEN CLOTH";
						c_a21['PLASTIC FILM,MULTILAYER FILM,SHRINK,WRAP FILM'] = "SELECT SUB_CATEGORY|SHRINK FILMS|POLYOLEFIN SHRINK FILM|HDPE ROLLS|POLYURATHIN SHEETS ABD ROLLS";
						c_a21['BLOW MOULDING PLASTIC BARRELS,BOTTLES CANS CONTAINERS,TANKS'] = "SELECT SUB_CATEGORY|PLASTIC BOTTLES UPTO 10 LTR|PLASTIC CANS  UPTO 50 LTR|PLASTIC BARRELS UPTO 100 LTR|PLASTIC TANKS UPTO 500 LTR";
						c_a21['CRAFT PAPER ROLLS AND BOARDS,PACKING AND WRAPPING PAPER'] = "SELECT SUB_CATEGORY|TISSUE GRADES|ABSORBENT KRAFT|MEDICINE PAPER JUMBO ROLL|CARBONLESS PAPER|THERMALPAPER|WHITE 2 PLY WRAPPING PAPER|WHITE BUBBLE PAPER|MACHINE WRAP PAPER";
						c_a21['WOODEN BOXES,CASES,CRATES PLYWOOD BOXES,CABLE DRUMS,PALLETS'] = "SELECT SUB_CATEGORY|RUBBER/PINE WOOD BOXES|WOODEN CABLE DRUMS|INDUSTRIAL WOODEN BOXES|PLYWOOD / MDF BOXES|RUBBER / PINE WOOD PALLETS|WOODEN CRATES";
						c_a21['PAPER TUBE,CONES,CORES AND CONTAINERS'] = "SELECT SUB_CATEGORY|PAPER TUBE  /CORE / CONES|PAPER DRUMS|COMPOSITE PAPER CONTAINER|PAPER FOOD CONTAINER|PAPER TUBE CONTAINER";
						c_a21['THERMOCOL PACKING PRODUCTS'] = "SELECT SUB_CATEGORY|EPS LOOSE FILLER|EPS BOX|BEAN BOX FILTER|THERMOCOL BOX|FILLER SLABS|INSULATION SHEET|COLD CHAIN PACKING SHEET";
						c_a21['COTTON BAGS'] = "SELECT SUB_CATEGORY|COTTON HAND BAGS PLAIN|LOOP HANDLE COTTON BAG|COTTON HAND BAG PRINTED|COTTON PURSES|BACKPACK|COSMATIC ZIPPER BAG|NON WOVEN BAGS";
						c_a21['ADHESIVE TAPES'] = "SELECT SUB_CATEGORY|BOPP TAPES|HDPE TAPES|PVC EDGE BANDS|MASKING TAPE|BUTYL TAPE|POLYPROPYLENE TAPE|PRINTED TAPE|BROWN TAPE|ALUMINIUM FOIL TAPE|DUCT TAPE|FILAMENT TAPE|REINFORCED PAPER TAPE";
						c_a21['LABEL,STICKERS AND SCREEN PRINTING PAPERS'] = "SELECT SUB_CATEGORY|PIN MAILER|PRE PRINTED STATIONERY|WRITING PAPER|PRINTED BUTTER PAPER|EPOXY DOMED LABELS|DOME LABELS|METAL BADGES|SAFETY SIGN BOARD|VINYL STICKERS|POLYCARBONATE STICKERS";
						c_a21['TARRAULINES,PLASTIC,POLY,HDP,CANVAS'] = "SELECT SUB_CATEGORY|PLASIC  TARPAULINES (HDPE,LDPE,PP)|CANVAS TARPAULIN|COTTON TARPAULIN|PVC TARPAULIN|FIRE RETARDANT TARPAULIN|NYLON TARPAULIN";
						c_a21['PLASTIC STRAPS AND SEALS'] = "SELECT SUB_CATEGORY|WATCH STRAPS|BELT STRAP|NYLON STRAP|SAFETY STRAP|TIE DOWN STRAP|STRAPING ROLLS(PP,GREEN,NYLON,)|STRAPING SEALER(PET,HEAVY DUTY,STEEL)|STRAPING SEAL(PET,STEEL,METAL)|NATO STRAP|CONTAINER SEAL|SECURITY TIE-STRAP LOCK|X-STRAP";
						c_a21['PAPER BAGS(PRINTED AND NON-PRINTED)'] = "SELECT SUB_CATEGORY|CUSTOM PAPER BAGS|FRAKTA PAPER BAG WITH HANDLE|IVORY PAPER BAG|BROWN PAPER BAG|LUXURY PAPER BAGS";

						//12.

						//13.SERVICE INDUSTRY

						c_a21['ADVERTISING & DIGITAL MARKETING'] = "SELECT SUB_CATEGORY|PROMOTIONAL ITEMS FOR BRANDING|LED DISPLAY BOARDS AND BANNERS|DIGITAL MARKETING SERVICES|NEWS PAPER AND T.V ADVERTISEMENT|DOOR TO DOOR MARKETING|TELEMARKETING";
						c_a21['ARCHITECTURAL CONSULTANTS'] = "SELECT SUB_CATEGORY|VASTU CONSULTANTS|ARCHITECTURAL DESIGNING SERVICES|ENVIRONMENTAL DESIGN|COLD STORAGE DESIGN|CITY PLANNING SERVICE|INTERIOR DESIGNERS";
						c_a21['BIO REASEARCH CENTRE'] = "SELECT SUB_CATEGORY|FORENSIC BIOLOGIST|MICROBIOLOGIST|MARINE BIOLOGIST|ECOLOGIST";
						c_a21['CIVIL CONTRACTORS'] = "SELECT SUB_CATEGORY|LABOUR CONTRACTORS|RESIDENTIAL CONSTRUCTION SERVICES|ROAD CONSTRUCTION|INDUSTRIAL CIVIL SERVICES|CIVIL ENGIEERING SERVICES|COMMERCIAL CIVIL SERVICES|SPECIALISED CIVIL JOBS|MINING CONSTRUCTION SERVICES|LANDSCAPE CARE AND MAINTANANCE SERVICE|SCAFFOLDING";
						c_a21['CUSTOMS HANDLING AGENTS AND IMPORT WAREHOUSING'] = "SELECT SUB_CATEGORY|CUSTOM ADVISORY SERVICES|HAZARDOUS HANDLING SERVICES|CUSTOM CLEARANCE SERVICES|IMPORT STORAGE AND WAREHOUSING SERVICES|FREIGHT FORWARDING SERVICES";
						c_a21['CNC MACHINING SERVICES'] = "";
						c_a21['COURIER SERVICES'] = "SELECT SUB_CATEGORY|INTERNATIONAL COURIER SERVICES|DOMESTIC COURIER SERVICES";
						c_a21['ELECTRICAL CONSULTANTS AND CONTRACTORS'] = "INDUSTRIAL ELECTRICAL SERVICES|HOUSING ELECTRICAL SERVICES|ELCTRICAL MOTOR WINDING AND REPAIRING SERVICES|ELECTRICAL TURNKEYS SERVICES";
						c_a21['ELECTRONIC PCB DESIGING WORK'] = "";
						c_a21['PLATING AND GALVANISING'] = "SELECT SUB_CATEGORY|ELECTROPLATING|HOP DIP|HARDCHROME PLATING|POWDER COATING|HEAT TREATMENT";
						c_a21['FINANCE & INVESTMENT CONSULTANTS'] = "SELECT SUB_CATEGORY|PROJECT FINANCE|CORPORATE FINANCE|3 RD PARTY CFO|STATUTORY GOVT COMPLIENCES|RETAIL FINANCIAL SERVICES|FINANACIAL ANALYTICS SERVICES|FINANCIAL DUE-DELLIGENCE|TRANSACTION ADVISORY SERVICES|FINANCIAL RESTRUCTURING SERVICES";
						c_a21['FIRE FIGHTING SERVICES'] = "SELECT SUB_CATEGORY|INDUSTRIAL SERVICES|COMMERCIAL SERVICES|MARINE SERVICES|AIR SERVICES";
						c_a21['SURFACE PREPARATION  SERVICES'] = "SELECT SUB_CATEGORY|MILLING|TURNING|GRINDING|SHORT BLASTING|LASER CUTTING|GEAR CUTTING";
						c_a21['FOOD & CANTEEN SERVICES'] = "SELECT SUB_CATEGORY|CANTEEN SERVICES PLANT|COLLEGE CANTEEN CONTRACTORS|CATERING SERVICES|CORPORATE CATERING SERVICES";
						c_a21['FOUNDRY'] = "SELECT SUB_CATEGORY|IRON AND STEEL CASTING|ALUMINIUM CASTING|ALLOY CASTING";
						c_a21['LADGING AND BOARDING SERVICES'] = "SELECT SUB_CATEGORY|HOTEL UPTO 3 STARS|HOTEL UPTO 5 STARS|HOTEL UPTO 7 STARS|BUDGET HOTELS|RESORTS|BANQUET HALLS";
						c_a21['HOUSE KEEPING CONTRACTORS'] = "SELECT SUB_CATEGORY|HOUSEKEEPING SERVICES|CORPORATE HOUSE KEEPING SERVICES|CLEANING SERVICES";
						c_a21['HUMAN RESOURCE SERVICES'] = "SELECT SUB_CATEGORY|CONFLICT MANAGEMENT|EMPLOYEE ASSISSTANCE PROGRAMS|AUDIT SERVICES|ANALYTICS SERVICES|RECRUITEMENT SERVICES LABOUR AND STAFF|HR OUT SOURCING SERVICES";
						c_a21['INSURANCE CONSULTANTS'] = "SELECT SUB_CATEGORY|INDUSTRIAL INSURANCE SERVICES|PERSONAL INSURANCE SERVICES|AUTOMOTIVE INSURANCE|TRAVEL INSURANCE|TRANSPORT INSURANCE|GOODS INSURANCE|HEALTH INSURANCE ";
						c_a21['LEGAL CONSULTANTS'] = "SELECT SUB_CATEGORY|ADMINISTRATIVE  LAW ATTORNEYS|CYBER LAW SERVICES|INSURANCE LAW ATTORNEYS|IMMIGRATION LAW SERVICES|ENVIRONMENTAL LAW ATTORNEYS";
						c_a21['FABRICATION SERVICES'] = "SELECT SUB_CATEGORY|STEEL FABRICATION|ALLOY FABRICATION|ALUMINIUM FABRICATION|PIPE LINE FABRICATION|PLASTIC FABRICATION";
						c_a21['MECHANICAL CONSULTANTS AND CONTRACTORS'] = "SELECT SUB_CATEGORY|INDUSTRIAL MECHANICAL SERVICES|COMMERCIAL MECHANICAL SERVICES|MECHANICALS PUMPS REPAIRING|POWER GENERATOR REPAIRING|SPECIALISED MECHANICAL SERVICES|ENGINE BORING SERVICES";
						c_a21['MATERIAL TESTING SERVICES'] = "SELECT SUB_CATEGORY|METALS|CHEMICALS|PHARMACEUTICALS|PLASTICS AND POLYMERS|SOIL AND FERTILIZER|FOOD PRODUCTS|WATER TESTING";
						c_a21['OIL CLEANING AND FILTRATION'] = "";
						c_a21['DIE,MOULD AND PATTERN MAKING SERVICES'] = "SELECT SUB_CATEGORY|DIE MAKING|MOULD MAKING|PATTERN MAKING";
						c_a21['PLUMBING CONTRACTORS'] = "SELECT SUB_CATEGORY|INDUSTRIAL PLUMBING|WATER SYSTEM PLUMBING SERVICES|HOUSING PLUMBING SERVICES|SANITARY PLUNBING SERVICES|AGRICULTURAL SERVICES";
						c_a21['PROCESS CONTROL MANAGEMENT SYSTEM'] = "";
						c_a21['REPAIR AND MAINTAINENCE SERVICES'] = "SELECT SUB_CATEGORY|MEASURING AND TESTING EQUIPMENTS|AUTOMOBILES|STORAGE TANKS|BUILDING CONSTRUCTION EQUIPMENTS|GENERATORS AND TRANSFORMER";
						c_a21['SECURITY SERVICES'] = "SELECT SUB_CATEGORY|PERSONAL  SECURITY GUARD SERVICES|EXECUTIVE PROTECTION SECURITY SERVICES|SECURITY GUARDS|INDUSTRIAL SECURITY AND DOG SERVICE";
						c_a21['STORAGE AND WAREHOUSING'] = "SELECT SUB_CATEGORY|CHEMICAL|COLD STORAGES|HAZARDOUS CHEMICALS|CONTAINER WAREHOUSING|BONDED WAREHOUSING|OUTSOURCING SERVICES";
						c_a21['TAX CONSULTANTS'] = "SELECT SUB_CATEGORY|INCOME  TAX CONSULTANT|IMPORT EXPORT TAX CONSULTANT|GST TAX CONSULTANT|PROPERTY  TAX CONSULTANT|INTERNATIONAL TAX CONSULTANT";
						c_a21['TRASPORTATION SERVICES'] = "SELECT SUB_CATEGORY|TRUCK TRANSPORTATION|TANKER TRANSPORTATION|CONTAINER TRANSPORTATION|TAXI PROVIDER|BUS TRANSPORTATION|PROJECT TRANSPORTATION(ODC)|PART LOAD SERVICES";

						$('#industry1').change(function() {
							var c1 = $(this).val();
							var state_arr1 = s_a21[c1].split("|");
							$('#category1').empty();
							$('#sub_category1').empty();
							if (c1 == 0) {
								$('#category1').append($('<option>', {
									value : '0',
									text : 'Select Category',
								}, '</option>'));
							} else {
								$.each(state_arr1, function(k, item_state) {
									$('#category1').append($('<option>', {
										value : item_state,
										text : item_state,
									}, '</option>'));
								});
							}
							$('#sub_category1').append($('<option>', {
								value : '0',
								text : 'Select Sub-Category',
							}, '</option>'));
						});

						$('#category1').change(function() {
							var s1 = $(this).val();
							if (s1 == 'Select State') {
								$('#sub_category1').empty();
								$('#sub_category1').append($('<option>', {
									value : '0',
									text : 'Select Sub-Category',
								}, '</option>'));
							}
							var city_arr1 = c_a21[s1].split("|");
							$('#sub_category1').empty();

							$.each(city_arr1, function(l, item_city) {
								$('#sub_category1').append($('<option>', {
									value : item_city,
									text : item_city,
								}, '</option>'));
							});

						});
					});
</script>


<script type="text/javascript">
	$(document)
			.ready(
					function() {
						// Countries
						var country_arr2 = new Array("SELECT COUNTRY",
								"AFGHANISTAN", "ALBANIA", "ALGERIA", "ANDORRA",
								"ANGOLA", "ANTIGUA AND BARBUDA", "ARGENTINA",
								"ARMENIA", "AUSTRALIA", "AUSTRIA",
								"AZERBAIJAN", "BAHAMAS", "BAHRAIN",
								"BANGLADESH", "BARBADOS", "BELARUS", "BELGIUM",
								"BELIZE", "BENIN", "BHUTAN", "BOLIVIA",
								"BOSNIA AND HERZEGOVINA", "BOTSWANA", "BRAZIL",
								"BRUNEI", "BULGARIA", "BURKINA FASO",
								"BURUNDI", "CABO VERDE", "CAMBODIA",
								"CAMEROON", "CANADA",
								"CENTRAL AFRICAN REPUBLIC", "CHAD", "CHILE",
								"CHINA", "COLOMBIA", "COMOROS", "CONGO",
								"COSTA RICA", "COTE D'IVOIRE", "CROATIA",
								"CUBA", "CYPRUS", "CZECH REPUBLIC (CZECHIA)",
								"DENMARK", "DJIBOUTI", "DOMINICA",
								"DOMINICAN REPUBLIC", "DR CONGO", "ECUADOR",
								"EGYPT", "ELSALVADOR", "EQUATORIALGUINEA",
								"ERITREA", "ESTONIA", "ESWATINI", "ETHIOPIA",
								"FIJI", "FINLAND", "FRANCE", "GABON", "GAMBIA",
								"GEORGIA", "GERMANY", "GHANA", "GREECE",
								"GRENADA", "GUATEMALA", "GUINEA",
								"GUINEA BISSAU", "GUYANA", "HAITI", "HOLY SEE",
								"HONDURAS", "HUNGARY", "ICELAND", "INDIA",
								"INDONESIA", "IRAN", "IRAQ", "IRELAND",
								"ISRAEL", "ITALY", "JAMAICA", "JAPAN",
								"JORDAN", "KAZAKHSTAN", "KENYA", "KIRIBATI",
								"KUWAIT", "KYRGYZSTAN", "LAOS", "LATVIA",
								"LEBANON", "LESOTHO", "LIBERIA", "LIBYA",
								"LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG",
								"MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES",
								"MALI", "MALTA", "MARSHALL ISLANDS",
								"MAURITANIA", "MAURITIUS", "MEXICO",
								"MICRONESIA", "MOLDOVA", "MONACO", "MONGOLIA",
								"MONTENEGRO", "MOROCCO", "MOZAMBIQUE",
								"MYANMAR", "NAMIBIA", "NAURU", "NEPAL",
								"NETHERLANDS", "NEW ZEALAND", "NICARAGUA",
								"NIGER", "NIGERIA", "NORTH KOREA",
								"NORTH MACEDONIA", "NORWAY", "OMAN",
								"PAKISTAN", "PALAU", "PANAMA",
								"PAPUA NEW GUINEA", "PARAGUAY", "PERU",
								"PHILIPPINES", "POLAND", "PORTUGAL", "QATAR",
								"ROMANIA", "RUSSIA", "RWANDA",
								"SAINT KITTS AND NEVIS", "SAINT LUCIA",
								"SAMOA", "SAN MARINO", "SAO TOME AND PRINCIPE",
								"SAUDI ARABIA", "SENEGAL", "SERBIA",
								"SEYCHELLES", "SIERRA LEONE", "SINGAPORE",
								"SLOVAKIA", "SLOVENIA", "SOLOMON ISLANDS",
								"SOMALIA", "SOUTH AFRICA", "SOUTH KOREA",
								"SOUTH SUDAN", "SPAIN", "SRI LANKA",
								"ST. VINCENT AND GRENADINES",
								"STATE OF PALESTINE", "SUDAN", "SURINAME",
								"SWEDEN", "SWITZERLAND", "SYRIA", "TAIWAN",
								"TAJIKISTAN", "TANZANIA", "THAILAND",
								"TIMOR-LESTE", "TOGO", "TONGA",
								"TRINIDAD AND TOBAGO", "TUNISIA", "TURKEY",
								"TURKMENISTAN", "TUVALU", "UGANDA", "UKRAINE",
								"UNITED ARAB EMIRATES", "UNITED KINGDOM",
								"UNITED STATES", "URUGUAY", "UZBEKISTAN",
								"VANUATU", "VENEZUELA", "VIETNAM", "YEMEN",
								"ZAMBIA", "ZIMBABWE");

						$.each(country_arr2, function(m, item) {
							$('#country2').append($('<option>', {

								value : m,
								text : item,
							}, '</option>'));
						});

						// States
						var s_a2 = new Array();

						s_a2[0] = "SELECT COUNTRY";
						s_a2[1] = "Select State|Badakhshan|Badghis|Baghlan|Balkh|Bamyan|Daykundi|Farah|Faryab|Ghazni|Ghor|Helmand|Herat|Jowzjan|Kabul|Kandahar|Kapisa|Khost|Kunar|Kunduz|Laghman|Logar|Nangarhar|Nimruz|Nuristan|Paktia|Paktika|Panjshir|Parwan|Samangan|Sar-e Pol|Takhar|Uruzgan|Wardak|Zabul";
						s_a2[2] = "Select State|ANDHRAPRADESH|KARNATAKA|TAMILNADU|DELHI|GOA|W-BENGAL|GUJARAT|MADHYAPRADESH|MAHARASHTRA|RAJASTHAN";
						s_a2[3] = "Select State|Adrar|Aïn Defla|Aïn Témouchent|Algiers|Annaba|Batna|Béchar|Béjaïa|Béni Abbès|Biskra|Blida	          |Bordj Baji Mokhtar|Bordj Bou Arréridj|Bouïra|Boumerdès|Chlef|Constantine|Djanet|Djelfa|El Bayadh|El M'Ghair|El Menia|El Oued|El Tarf|Ghardaïa|Guelma|Illizi|In Guezzam|In Salah|Jijel|Khenchela|Laghouat|M'Sila|Mascara|Médéa|Mila|Mostaganem|Naâma|Oran|Ouargla|Ouled Djellal|Oum El Bouaghi|Relizane|Saïda|Sétif|Sidi Bel Abbès|Skikda|Souk Ahras|Tamanrasset|Tébessa|Tiaret|Timimoun|Tipaza|Tissemsilt|Tizi Ouzou|Tlemcen|Touggourt";
						s_a2[4] = "Select State|NEWJERSEY|ILLINOIS";
						s_a2[5] = "Select State|DUBAI";
						s_a2[6] = "Select State|";
						s_a2[7] = "Select State|";
						s_a2[8] = "Select State|";
						s_a2[9] = "Select State|";
						s_a2[10] = "Select State|";
						s_a2[11] = "Select State|";
						s_a2[12] = "Select State|";
						s_a2[13] = "Select State|";
						s_a2[14] = "Select State|";
						s_a2[15] = "Select State|";
						s_a2[16] = "Select State|";
						s_a2[17] = "Select State|";
						s_a2[18] = "Select State|";
						s_a2[19] = "Select State|";
						s_a2[20] = "Select State|";
						s_a2[21] = "Select State|";
						s_a2[22] = "Select State|";
						s_a2[23] = "Select State|";
						s_a2[24] = "Select State|";
						s_a2[25] = "Select State|";
						s_a2[26] = "Select State|";
						s_a2[27] = "Select State|";
						s_a2[28] = "Select State|";
						s_a2[29] = "Select State|";
						s_a2[30] = "Select State|";
						s_a2[31] = "Select State|";
						s_a2[32] = "Select State|";
						s_a2[33] = "Select State|";
						s_a2[34] = "Select State|";
						s_a2[35] = "Select State|";
						s_a2[36] = "Select State|";
						s_a2[37] = "Select State|";
						s_a2[38] = "Select State|";
						s_a2[39] = "Select State|";
						s_a2[40] = "Select State|";
						s_a2[41] = "Select State|";
						s_a2[42] = "Select State|";
						s_a2[43] = "Select State|";
						s_a2[44] = "Select State|";
						s_a2[45] = "Select State|";
						s_a2[46] = "Select State|";
						s_a2[47] = "Select State|";
						s_a2[48] = "Select State|";
						s_a2[49] = "Select State|";
						s_a2[50] = "Select State|";
						s_a2[51] = "Select State|";
						s_a2[52] = "Select State|";
						s_a2[53] = "Select State|";
						s_a2[54] = "Select State|";
						s_a2[55] = "Select State|";
						s_a2[56] = "Select State|";
						s_a2[57] = "Select State|";
						s_a2[58] = "Select State|";
						s_a2[59] = "Select State|";
						s_a2[60] = "Select State|";
						s_a2[61] = "Select State|";
						s_a2[62] = "Select State|";
						s_a2[63] = "Select State|";
						s_a2[64] = "Select State|";
						s_a2[65] = "Select State|";
						s_a2[66] = "Select State|";
						s_a2[67] = "Select State|";
						s_a2[68] = "Select State|";
						s_a2[69] = "Select State|";
						s_a2[70] = "Select State|";
						s_a2[71] = "Select State|";
						s_a2[72] = "Select State|";
						s_a2[73] = "Select State|";
						s_a2[74] = "Select State|";
						s_a2[75] = "Select State|";
						s_a2[76] = "Select State|";
						s_a2[77] = "Select State|";
						s_a2[78] = "SELECT STATE|Andaman & Nicobar|Andhra Pradesh|Arunachal Pradesh|Assam|Bihar|Chandigarh|Chhattisgarh|Dadra & Nagar Haveli|Daman & Diu|Delhi|Goa|Gujarat|Haryana|Himachal Pradesh|Jammu & Kashmir|Jharkhand|Karnataka|Kerala|Lakshadweep|Madhya Pradesh|Maharashtra|Manipur|Meghalaya|Mizoram|Nagaland|Orissa|Pondicherry|Punjab|Rajasthan|Sikkim|Tamil Nadu|Tripura|Uttar Pradesh|Uttaranchal|West Bengal";
						s_a2[79] = "Select State|";
						s_a2[80] = "Select State|";
						s_a2[81] = "Select State|";
						s_a2[82] = "Select State|";
						s_a2[83] = "Select State|";
						s_a2[84] = "Select State|";
						s_a2[85] = "Select State|";
						s_a2[86] = "Select State|";
						s_a2[87] = "Select State|";
						s_a2[88] = "Select State|";
						s_a2[89] = "Select State|";
						s_a2[90] = "Select State|";
						s_a2[91] = "Select State|";
						s_a2[92] = "Select State|";
						s_a2[93] = "Select State|";
						s_a2[94] = "Select State|";
						s_a2[95] = "Select State|";
						s_a2[96] = "Select State|";
						s_a2[97] = "Select State|";
						s_a2[98] = "Select State|";
						s_a2[99] = "Select State|";
						s_a2[100] = "Select State|";
						s_a2[101] = "Select State|";
						s_a2[102] = "Select State|";
						s_a2[103] = "Select State|";
						s_a2[104] = "Select State|";
						s_a2[105] = "Select State|";
						s_a2[106] = "Select State|";
						s_a2[107] = "Select State|";
						s_a2[108] = "Select State|";
						s_a2[109] = "Select State|";
						s_a2[110] = "Select State|";
						s_a2[111] = "Select State|";
						s_a2[112] = "Select State|";
						s_a2[113] = "Select State|";
						s_a2[114] = "Select State|";
						s_a2[115] = "Select State|";
						s_a2[116] = "Select State|";
						s_a2[117] = "Select State|";
						s_a2[118] = "Select State|";
						s_a2[119] = "Select State|";
						s_a2[120] = "Select State|";
						s_a2[121] = "Select State|";
						s_a2[122] = "Select State|";
						s_a2[123] = "Select State|";
						s_a2[124] = "Select State|";
						s_a2[125] = "Select State|";
						s_a2[126] = "Select State|";
						s_a2[127] = "Select State|";
						s_a2[128] = "Select State|";
						s_a2[129] = "Select State|";
						s_a2[130] = "Select State|";
						s_a2[131] = "Select State|";
						s_a2[132] = "Select State|";
						s_a2[133] = "Select State|";
						s_a2[134] = "Select State|";
						s_a2[135] = "Select State|";
						s_a2[136] = "Select State|";
						s_a2[137] = "Select State|";
						s_a2[138] = "Select State|";
						s_a2[139] = "Select State|";
						s_a2[140] = "Select State|";
						s_a2[141] = "Select State|";
						s_a2[142] = "Select State|";
						s_a2[143] = "Select State|";
						s_a2[144] = "Select State|";
						s_a2[145] = "Select State|";
						s_a2[146] = "Select State|";
						s_a2[147] = "Select State|";
						s_a2[148] = "Select State|";
						s_a2[149] = "Select State|";
						s_a2[150] = "Select State|";
						s_a2[151] = "Select State|";
						s_a2[152] = "Select State|";
						s_a2[153] = "Select State|";
						s_a2[154] = "Select State|";
						s_a2[155] = "Select State|";
						s_a2[156] = "Select State|";
						s_a2[157] = "Select State|";
						s_a2[158] = "Select State|";
						s_a2[159] = "Select State|";
						s_a2[160] = "Select State|";
						s_a2[161] = "Select State|";
						s_a2[162] = "Select State|";
						s_a2[163] = "Select State|";
						s_a2[164] = "Select State|";
						s_a2[165] = "Select State|";
						s_a2[166] = "Select State|";
						s_a2[167] = "Select State|";
						s_a2[168] = "Select State|";
						s_a2[169] = "Select State|";
						s_a2[170] = "Select State|";
						s_a2[171] = "Select State|";
						s_a2[172] = "Select State|";
						s_a2[173] = "Select State|";
						s_a2[174] = "Select State|";
						s_a2[175] = "Select State|";
						s_a2[176] = "Select State|";
						s_a2[177] = "Select State|";
						s_a2[178] = "Select State|";
						s_a2[179] = "Select State|";
						s_a2[180] = "Select State|";
						s_a2[181] = "Select State|";
						s_a2[182] = "Select State|";
						s_a2[183] = "Select State|";
						s_a2[184] = "Select State|";
						s_a2[185] = "Select State|";
						s_a2[186] = "Select State|";
						s_a2[187] = "Select State|";
						s_a2[188] = "Select State|";
						s_a2[189] = "Select State|";
						s_a2[190] = "Select State|";
						s_a2[191] = "Select State|";
						s_a2[192] = "Select State|";
						s_a2[193] = "Select State|";
						s_a2[194] = "Select State|";
						s_a2[195] = "Select State|";
						s_a2[196] = "Select State|";

						// Cities
						var c_a2 = new Array();

						c_a2['Andaman & Nicobar'] = " Alipur | Andaman Island | Anderson Island | Arainj-Laka-Punga | Austinabad | Bamboo Flat | Barren Island | Beadonabad | Betapur | Bindraban | Bonington | Brookesabad | Cadell Point | Calicut | Chetamale | Cinque Islands | Defence Island | Digilpur | Dolyganj | Flat Island | Geinyale | Great Coco Island | Haddo | Havelock Island | Henry Lawrence Island | Herbertabad | Hobdaypur | Ilichar | Ingoie | Inteview Island | Jangli Ghat | Jhon Lawrence Island | Karen | Kartara | KYD Islannd | Landfall Island | Little Andmand | Little Coco Island | Long Island | Maimyo | Malappuram | Manglutan | Manpur | Mitha Khari | Neill Island | Nicobar Island | North Brother Island | North Passage Island | North Sentinel Island | Nothen Reef Island | Outram Island | Pahlagaon | Palalankwe | Passage Island | Phaiapong | Phoenix Island | Port Blair | Preparis Island | Protheroepur | Rangachang | Rongat | Rutland Island | Sabari | Saddle Peak | Shadipur | Smith Island | Sound Island | South Sentinel Island | Spike Island | Tarmugli Island | Taylerabad | Titaije | Toibalawe | Tusonabad | West Island | Wimberleyganj | Yadita";
						c_a2['Andhra Pradesh'] = "Achampet | Adilabad | Adoni | Alampur | Allagadda | Alur | Amalapuram | Amangallu | Anakapalle | Anantapur | Andole | Araku | Armoor | Asifabad | Aswaraopet | Atmakur | B. Kothakota | Badvel | Banaganapalle | Bandar | Bangarupalem | Banswada | Bapatla | Bellampalli | Bhadrachalam | Bhainsa | Bheemunipatnam | Bhimadole | Bhimavaram | Bhongir | Bhooragamphad | Boath | Bobbili | Bodhan | Chandoor | Chavitidibbalu | Chejerla | Chepurupalli | Cherial | Chevella | Chinnor | Chintalapudi | Chintapalle | Chirala | Chittoor | Chodavaram | Cuddapah | Cumbum | Darsi | Devarakonda | Dharmavaram | Dichpalli | Divi | Donakonda | Dronachalam | East Godavari | Eluru | Eturnagaram | Gadwal | Gajapathinagaram | Gajwel | Garladinne | Giddalur | Godavari | Gooty | Gudivada | Gudur | Guntur | Hindupur | Hunsabad | Huzurabad | Huzurnagar | Hyderabad | Ibrahimpatnam | Jaggayyapet | Jagtial | Jammalamadugu | Jangaon | Jangareddygudem | Jannaram | Kadiri | Kaikaluru | Kakinada | Kalwakurthy | Kalyandurg | Kamalapuram | Kamareddy | Kambadur | Kanaganapalle | Kandukuru | Kanigiri | Karimnagar | Kavali | Khammam | Khanapur (AP) | Kodangal | Koduru | Koilkuntla | Kollapur | Kothagudem | Kovvur | Krishna | Krosuru | Kuppam | Kurnool | Lakkireddipalli | Madakasira | Madanapalli | Madhira | Madnur | Mahabubabad | Mahabubnagar | Mahadevapur | Makthal | Mancherial | Mandapeta | Mangalagiri | Manthani | Markapur | Marturu | Medachal | Medak | Medarmetla | Metpalli | Mriyalguda | Mulug | Mylavaram | Nagarkurnool | Nalgonda | Nallacheruvu | Nampalle | Nandigama | Nandikotkur | Nandyal | Narasampet | Narasaraopet | Narayanakhed | Narayanpet | Narsapur | Narsipatnam | Nazvidu | Nelloe | Nellore | Nidamanur | Nirmal | Nizamabad | Nuguru | Ongole | Outsarangapalle | Paderu | Pakala | Palakonda | Paland | Palmaneru | Pamuru | Pargi | Parkal | Parvathipuram | Pathapatnam | Pattikonda | Peapalle | Peddapalli | Peddapuram | Penukonda | Piduguralla | Piler | Pithapuram | Podili | Polavaram | Prakasam | Proddatur | Pulivendla | Punganur | Putturu | Rajahmundri | Rajampeta | Ramachandrapuram | Ramannapet | Rampachodavaram | Rangareddy | Rapur | Rayachoti | Rayadurg | Razole | Repalle | Saluru | Sangareddy | Sathupalli | Sattenapalle | Satyavedu | Shadnagar | Siddavattam | Siddipet | Sileru | Sircilla | Sirpur Kagaznagar | Sodam | Sompeta | Srikakulam | Srikalahasthi | Srisailam | Srungavarapukota | Sudhimalla | Sullarpet | Tadepalligudem | Tadipatri | Tanduru | Tanuku | Tekkali | Tenali | Thungaturthy | Tirivuru | Tirupathi | Tuni | Udaygiri | Ulvapadu | Uravakonda | Utnor | V.R. Puram | Vaimpalli | Vayalpad | Venkatgiri | Venkatgirikota | Vijayawada | Vikrabad | Vinjamuru | Vinukonda | Visakhapatnam | Vizayanagaram | Vizianagaram | Vuyyuru | Wanaparthy | Warangal | Wardhannapet | Yelamanchili | Yelavaram | Yeleswaram | Yellandu | Yellanuru | Yellareddy | Yerragondapalem | Zahirabad ";
						c_a2['Arunachal Pradesh'] = "Along | Anini | Anjaw | Bameng | Basar | Changlang | Chowkhem | Daporizo | Dibang Valley | Dirang | Hayuliang | Huri | Itanagar | Jairampur | Kalaktung | Kameng | Khonsa | Kolaring | Kurung Kumey | Lohit | Lower Dibang Valley | Lower Subansiri | Mariyang | Mechuka | Miao | Nefra | Pakkekesang | Pangin | Papum Pare | Passighat | Roing | Sagalee | Seppa | Siang | Tali | Taliha | Tawang | Tezu | Tirap | Tuting | Upper Siang | Upper Subansiri | Yiang Kiag ";
						c_a2['Assam'] = " Abhayapuri | Baithalangshu | Barama | Barpeta Road | Bihupuria | Bijni | Bilasipara | Bokajan | Bokakhat | Boko | Bongaigaon | Cachar | Cachar Hills | Darrang | Dhakuakhana | Dhemaji | Dhubri | Dibrugarh | Digboi | Diphu | Goalpara | Gohpur | Golaghat | Guwahati | Hailakandi | Hajo | Halflong | Hojai | Howraghat | Jorhat | Kamrup | Karbi Anglong | Karimganj | Kokarajhar | Kokrajhar | Lakhimpur | Maibong | Majuli | Mangaldoi | Mariani | Marigaon | Moranhat | Morigaon | Nagaon | Nalbari | Rangapara | Sadiya | Sibsagar | Silchar | Sivasagar | Sonitpur | Tarabarihat | Tezpur | Tinsukia | Udalgiri | Udalguri | UdarbondhBarpeta";
						c_a2['Bihar'] = "Adhaura | Amarpur | Araria | Areraj | Arrah | Arwal | Aurangabad | Bagaha | Banka | Banmankhi | Barachakia | Barauni | Barh | Barosi | Begusarai | Benipatti | Benipur | Bettiah | Bhabhua | Bhagalpur | Bhojpur | Bidupur | Biharsharif | Bikram | Bikramganj | Birpur | Buxar | Chakai | Champaran | Chapara | Dalsinghsarai | Danapur | Darbhanga | Daudnagar | Dhaka | Dhamdaha | Dumraon | Ekma | Forbesganj | Gaya | Gogri | Gopalganj | H.Kharagpur | Hajipur | Hathua | Hilsa | Imamganj | Jahanabad | Jainagar | Jamshedpur | Jamui | Jehanabad | Jhajha | Jhanjharpur | Kahalgaon | Kaimur (Bhabua) | Katihar | Katoria | Khagaria | Kishanganj | Korha | Lakhisarai | Madhepura | Madhubani | Maharajganj | Mahua | Mairwa | Mallehpur | Masrakh | Mohania | Monghyr | Motihari | Motipur | Munger | Muzaffarpur | Nabinagar | Nalanda | Narkatiaganj | Naugachia | Nawada | Pakribarwan | Pakridayal | Patna | Phulparas | Piro | Pupri | Purena | Purnia | Rafiganj | Rajauli | Ramnagar | Raniganj | Raxaul | Rohtas | Rosera | S.Bakhtiarpur | Saharsa | Samastipur | Saran | Sasaram | Seikhpura | Sheikhpura | Sheohar | Sherghati | Sidhawalia | Singhwara | Sitamarhi | Siwan | Sonepur | Supaul | Thakurganj | Triveniganj | Udakishanganj | Vaishali | Wazirganj";
						c_a2['Chandigarh'] = "Chandigarh | Mani Marja";
						c_a2['Chhattisgarh'] = "Ambikapur | Antagarh | Arang | Bacheli | Bagbahera | Bagicha | Baikunthpur | Balod | Balodabazar | Balrampur | Barpalli | Basana | Bastanar | Bastar | Bderajpur | Bemetara | Berla | Bhairongarh | Bhanupratappur | Bharathpur | Bhatapara | Bhilai | Bhilaigarh | Bhopalpatnam | Bijapur | Bilaspur | Bodla | Bokaband | Chandipara | Chhinagarh | Chhuriakala | Chingmut | Chuikhadan | Dabhara | Dallirajhara | Dantewada | Deobhog | Dhamda | Dhamtari | Dharamjaigarh | Dongargarh | Durg | Durgakondal | Fingeshwar | Gariaband | Garpa | Gharghoda | Gogunda | Ilamidi | Jagdalpur | Janjgir | Janjgir-Champa | Jarwa | Jashpur | Jashpurnagar | Kabirdham-Kawardha | Kanker | Kasdol | Kathdol | Kathghora | Kawardha | Keskal | Khairgarh | Kondagaon | Konta | Korba | Korea | Kota | Koyelibeda | Kuakunda | Kunkuri | Kurud | Lohadigundah | Lormi | Luckwada | Mahasamund | Makodi | Manendragarh | Manpur | Marwahi | Mohla | Mungeli | Nagri | Narainpur | Narayanpur | Neora | Netanar | Odgi | Padamkot | Pakhanjur | Pali | Pandaria | Pandishankar | Parasgaon | Pasan | Patan | Pathalgaon | Pendra | Pratappur | Premnagar | Raigarh | Raipur | Rajnandgaon | Rajpur | Ramchandrapur | Saraipali | Saranggarh | Sarona | Semaria | Shakti | Sitapur | Sukma | Surajpur | Surguja | Tapkara | Toynar | Udaipur | Uproda | Wadrainagar";
						c_a2['Dadra & Nagar Haveli'] = "Amal | Amli | Bedpa | Chikhli | Dadra & Nagar Haveli | Dahikhed | Dolara | Galonda | Kanadi | Karchond | Khadoli | Kharadpada | Kherabari | Kherdi | Kothar | Luari | Mashat | Rakholi | Rudana | Saili | Sili | Silvassa | Sindavni | Udva | Umbarkoi | Vansda | Vasona | Velugam";
						c_a2['Daman & Diu'] = "Brancavare | Dagasi | Daman | Diu | Magarvara | Nagwa | Pariali | Passo Covo";
						c_a2['Delhi'] = "Central Delhi | East Delhi | New Delhi | North Delhi | North East Delhi | North West Delhi | South Delhi | South West Delhi | West Delhi";
						c_a2['Goa'] = "Canacona | Candolim | Chinchinim | Cortalim | Goa | Jua | Madgaon | Mahem | Mapuca | Marmagao | Panji | Ponda | Sanvordem | Terekhol";
						c_a2['Gujarat'] = "Ahmedabad | Ahwa | Amod | Amreli | Anand | Anjar | Ankaleshwar | Babra | Balasinor | Banaskantha | Bansada | Bardoli | Bareja | Baroda | Barwala | Bayad | Bhachav | Bhanvad | Bharuch | Bhavnagar | Bhiloda | Bhuj | Billimora | Borsad | Botad | Chanasma | Chhota Udaipur | Chotila | Dabhoi | Dahod | Damnagar | Dang | Danta | Dasada | Dediapada | Deesa | Dehgam | Deodar | Devgadhbaria | Dhandhuka | Dhanera | Dharampur | Dhari | Dholka | Dhoraji | Dhrangadhra | Dhrol | Dwarka | Fortsongadh | Gadhada | Gandhi Nagar | Gariadhar | Godhra | Gogodar | Gondal | Halol | Halvad | Harij | Himatnagar | Idar | Jambusar | Jamjodhpur | Jamkalyanpur | Jamnagar | Jasdan | Jetpur | Jhagadia | Jhalod | Jodia | Junagadh | Junagarh | Kalawad | Kalol | Kapad Wanj | Keshod | Khambat | Khambhalia | Khavda | Kheda | Khedbrahma | Kheralu | Kodinar | Kotdasanghani | Kunkawav | Kutch | Kutchmandvi | Kutiyana | Lakhpat | Lakhtar | Lalpur | Limbdi | Limkheda | Lunavada | M.M.Mangrol | Mahuva | Malia-Hatina | Maliya | Malpur | Manavadar | Mandvi | Mangrol | Mehmedabad | Mehsana | Miyagam | Modasa | Morvi | Muli | Mundra | Nadiad | Nakhatrana | Nalia | Narmada | Naswadi | Navasari | Nizar | Okha | Paddhari | Padra | Palanpur | Palitana | Panchmahals | Patan | Pavijetpur | Porbandar | Prantij | Radhanpur | Rahpar | Rajaula | Rajkot | Rajpipla | Ranavav | Sabarkantha | Sanand | Sankheda | Santalpur | Santrampur | Savarkundla | Savli | Sayan | Sayla | Shehra | Sidhpur | Sihor | Sojitra | Sumrasar | Surat | Surendranagar | Talaja | Thara | Tharad | Thasra | Una-Diu | Upleta | Vadgam | Vadodara | Valia | Vallabhipur | Valod | Valsad | Vanthali | Vapi | Vav | Veraval | Vijapur | Viramgam | Visavadar | Visnagar | Vyara | Waghodia | Wankaner";
						c_a2['Haryana'] = "Adampur Mandi | Ambala | Assandh | Bahadurgarh | Barara | Barwala | Bawal | Bawanikhera | Bhiwani | Charkhidadri | Cheeka | Chhachrauli | Dabwali | Ellenabad | Faridabad | Fatehabad | Ferojpur Jhirka | Gharaunda | Gohana | Gurgaon | Hansi | Hisar | Jagadhari | Jatusana | Jhajjar | Jind | Julana | Kaithal | Kalanaur | Kalanwali | Kalka | Karnal | Kosli | Kurukshetra | Loharu | Mahendragarh | Meham | Mewat | Mohindergarh | Naraingarh | Narnaul | Narwana | Nilokheri | Nuh | Palwal | Panchkula | Panipat | Pehowa | Ratia | Rewari | Rohtak | Safidon | Sirsa | Siwani | Sonipat | Tohana | Tohsam | Yamunanagar";
						c_a2['Himachal Pradesh'] = "Amb | Arki | Banjar | Bharmour | Bilaspur | Chamba | Churah | Dalhousie | Dehra Gopipur | Hamirpur | Jogindernagar | Kalpa | Kangra | Kinnaur | Kullu | Lahaul | Mandi | Nahan | Nalagarh | Nirmand | Nurpur | Palampur | Pangi | Paonta | Pooh | Rajgarh | Rampur Bushahar | Rohru | Shimla | Sirmaur | Solan | Spiti | Sundernagar | Theog | Udaipur | Una";
						c_a2['Jammu & Kashmir'] = "Akhnoor | Anantnag | Badgam | Bandipur | Baramulla | Basholi | Bedarwah | Budgam | Doda | Gulmarg | Jammu | Kalakot | Kargil | Karnah | Kathua | Kishtwar | Kulgam | Kupwara | Leh | Mahore | Nagrota | Nobra | Nowshera | Nyoma | Padam | Pahalgam | Patnitop | Poonch | Pulwama | Rajouri | Ramban | Ramnagar | Reasi | Samba | Srinagar | Udhampur | Vaishno Devi";
						c_a2['Jharkhand'] = "Bagodar | Baharagora | Balumath | Barhi | Barkagaon | Barwadih | Basia | Bermo | Bhandaria | Bhawanathpur | Bishrampur | Bokaro | Bolwa | Bundu | Chaibasa | Chainpur | Chakardharpur | Chandil | Chatra | Chavparan | Daltonganj | Deoghar | Dhanbad | Dumka | Dumri | Garhwa | Garu | Ghaghra | Ghatsila | Giridih | Godda | Gomia | Govindpur | Gumla | Hazaribagh | Hunterganj | Ichak | Itki | Jagarnathpur | Jamshedpur | Jamtara | Japla | Jharmundi | Jhinkpani | Jhumaritalaiya | Kathikund | Kharsawa | Khunti | Koderma | Kolebira | Latehar | Lohardaga | Madhupur | Mahagama | Maheshpur Raj | Mandar | Mandu | Manoharpur | Muri | Nagarutatri | Nala | Noamundi | Pakur | Palamu | Palkot | Patan | Rajdhanwar | Rajmahal | Ramgarh | Ranchi | Sahibganj | Saraikela | Simaria | Simdega | Singhbhum | Tisri | Torpa";
						c_a2['Karnataka'] = "Afzalpur | Ainapur | Aland | Alur | Anekal | Ankola | Arsikere | Athani | Aurad | Bableshwar | Badami | Bagalkot | Bagepalli | Bailhongal | Bangalore | Bangalore Rural | Bangarpet | Bantwal | Basavakalyan | Basavanabagewadi | Basavapatna | Belgaum | Bellary | Belthangady | Belur | Bhadravati | Bhalki | Bhatkal | Bidar | Bijapur | Biligi | Chadchan | Challakere | Chamrajnagar | Channagiri | Channapatna | Channarayapatna | Chickmagalur | Chikballapur | Chikkaballapur | Chikkanayakanahalli | Chikkodi | Chikmagalur | Chincholi | Chintamani | Chitradurga | Chittapur | Cowdahalli | Davanagere | Deodurga | Devangere | Devarahippargi | Dharwad | Doddaballapur | Gadag | Gangavathi | Gokak | Gowribdanpur | Gubbi | Gulbarga | Gundlupet | H.B.Halli | H.D. Kote | Haliyal | Hampi | Hangal | Harapanahalli | Hassan | Haveri | Hebri | Hirekerur | Hiriyur | Holalkere | Holenarsipur | Honnali | Honnavar | Hosadurga | Hosakote | Hosanagara | Hospet | Hubli | Hukkeri | Humnabad | Hungund | Hunsagi | Hunsur | Huvinahadagali | Indi | Jagalur | Jamkhandi | Jewargi | Joida | K.R. Nagar | Kadur | Kalghatagi | Kamalapur | Kanakapura | Kannada | Kargal | Karkala | Karwar | Khanapur | Kodagu | Kolar | Kollegal | Koppa | Koppal | Koratageri | Krishnarajapet | Kudligi | Kumta | Kundapur | Kundgol | Kunigal | Kurugodu | Kustagi | Lingsugur | Madikeri | Madugiri | Malavalli | Malur | Mandya | Mangalore | Manipal | Manvi | Mashal | Molkalmuru | Mudalgi | Muddebihal | Mudhol | Mudigere | Mulbagal | Mundagod | Mundargi | Murugod | Mysore | Nagamangala | Nanjangud | Nargund | Narsimrajapur | Navalgund | Nelamangala | Nimburga | Pandavapura | Pavagada | Puttur | Raibag | Raichur | Ramdurg | Ranebennur | Ron | Sagar | Sakleshpur | Salkani | Sandur | Saundatti | Savanur | Sedam | Shahapur | Shankarnarayana | Shikaripura | Shimoga | Shirahatti | Shorapur | Siddapur | Sidlaghatta | Sindagi | Sindhanur | Sira | Sirsi | Siruguppa | Somwarpet | Sorab | Sringeri | Sriniwaspur | Srirangapatna | Sullia | T. Narsipur | Tallak | Tarikere | Telgi | Thirthahalli | Tiptur | Tumkur | Turuvekere | Udupi | Virajpet | Wadi | Yadgiri | Yelburga | Yellapur";
						c_a2['Kerala'] = "Adimaly | Adoor | Agathy | Alappuzha | Alathur | Alleppey | Alwaye | Amini | Androth | Attingal | Badagara | Bitra | Calicut | Cannanore | Chetlet | Ernakulam | Idukki | Irinjalakuda | Kadamath | Kalpeni | Kalpetta | Kanhangad | Kanjirapally | Kannur | Karungapally | Kasargode | Kavarathy | Kiltan | Kochi | Koduvayur | Kollam | Kottayam | Kovalam | Kozhikode | Kunnamkulam | Malappuram | Mananthodi | Manjeri | Mannarghat | Mavelikkara | Minicoy | Munnar | Muvattupuzha | Nedumandad | Nedumgandam | Nilambur | Palai | Palakkad | Palghat | Pathaanamthitta | Pathanamthitta | Payyanur | Peermedu | Perinthalmanna | Perumbavoor | Punalur | Quilon | Ranni | Shertallai | Shoranur | Taliparamba | Tellicherry | Thiruvananthapuram | Thodupuzha | Thrissur | Tirur | Tiruvalla | Trichur | Trivandrum | Uppala | Vadakkanchery | Vikom | Wayanad";
						c_a2['Lakshadweep'] = "Agatti Island | Bingaram Island | Bitra Island | Chetlat Island | Kadmat Island | Kalpeni Island | Kavaratti Island | Kiltan Island | Lakshadweep Sea | Minicoy Island | North Island | South Island";
						c_a2['Madhya Pradesh'] = "Agar | Ajaigarh | Alirajpur | Amarpatan | Amarwada | Ambah | Anuppur | Arone | Ashoknagar | Ashta | Atner | Babaichichli | Badamalhera | Badarwsas | Badnagar | Badnawar | Badwani | Bagli | Baihar | Balaghat | Baldeogarh | Baldi | Bamori | Banda | Bandhavgarh | Bareli | Baroda | Barwaha | Barwani | Batkakhapa | Begamganj | Beohari | Berasia | Berchha | Betul | Bhainsdehi | Bhander | Bhanpura | Bhikangaon | Bhimpur | Bhind | Bhitarwar | Bhopal | Biaora | Bijadandi | Bijawar | Bijaypur | Bina | Birsa | Birsinghpur | Budhni | Burhanpur | Buxwaha | Chachaura | Chanderi | Chaurai | Chhapara | Chhatarpur | Chhindwara | Chicholi | Chitrangi | Churhat | Dabra | Damoh | Datia | Deori | Deosar | Depalpur | Dewas | Dhar | Dharampuri | Dindori | Gadarwara | Gairatganj | Ganjbasoda | Garoth | Ghansour | Ghatia | Ghatigaon | Ghorandogri | Ghughari | Gogaon | Gohad | Goharganj | Gopalganj | Gotegaon | Gourihar | Guna | Gunnore | Gwalior | Gyraspur | Hanumana | Harda | Harrai | Harsud | Hatta | Hoshangabad | Ichhawar | Indore | Isagarh | Itarsi | Jabalpur | Jabera | Jagdalpur | Jaisinghnagar | Jaithari | Jaitpur | Jaitwara | Jamai | Jaora | Jatara | Jawad | Jhabua | Jobat | Jora | Kakaiya | Kannod | Kannodi | Karanjia | Kareli | Karera | Karhal | Karpa | Kasrawad | Katangi | Katni | Keolari | Khachrod | Khajuraho | Khakner | Khalwa | Khandwa | Khaniadhana | Khargone | Khategaon | Khetia | Khilchipur | Khirkiya | Khurai | Kolaras | Kotma | Kukshi | Kundam | Kurwai | Kusmi | Laher | Lakhnadon | Lamta | Lanji | Lateri | Laundi | Maheshwar | Mahidpurcity | Maihar | Majhagwan | Majholi | Malhargarh | Manasa | Manawar | Mandla | Mandsaur | Manpur | Mauganj | Mawai | Mehgaon | Mhow | Morena | Multai | Mungaoli | Nagod | Nainpur | Narsingarh | Narsinghpur | Narwar | Nasrullaganj | Nateran | Neemuch | Niwari | Niwas | Nowgaon | Pachmarhi | Pandhana | Pandhurna | Panna | Parasia | Patan | Patera | Patharia | Pawai | Petlawad | Pichhore | Piparia | Pohari | Prabhapattan | Punasa | Pushprajgarh | Raghogarh | Raghunathpur | Rahatgarh | Raisen | Rajgarh | Rajpur | Ratlam | Rehli | Rewa | Sabalgarh | Sagar | Sailana | Sanwer | Sarangpur | Sardarpur | Satna | Saunsar | Sehore | Sendhwa | Seondha | Seoni | Seonimalwa | Shahdol | Shahnagar | Shahpur | Shajapur | Sheopur | Sheopurkalan | Shivpuri | Shujalpur | Sidhi | Sihora | Silwani | Singrauli | Sirmour | Sironj | Sitamau | Sohagpur | Sondhwa | Sonkatch | Susner | Tamia | Tarana | Tendukheda | Teonthar | Thandla | Tikamgarh | Timarani | Udaipura | Ujjain | Umaria | Umariapan | Vidisha | Vijayraghogarh | Waraseoni | Zhirnia";
						c_a2['Maharashtra'] = "Achalpur | Aheri | Ahmednagar | Ahmedpur | Ajara | Akkalkot | Akola | Akole | Akot | Alibagh | Amagaon | Amalner | Ambad | Ambejogai | Amravati | Arjuni Merogaon | Arvi | Ashti | Atpadi | Aurangabad | Ausa | Babhulgaon | Balapur | Baramati | Barshi Takli | Barsi | Basmatnagar | Bassein | Beed | Bhadrawati | Bhamregadh | Bhandara | Bhir | Bhiwandi | Bhiwapur | Bhokar | Bhokardan | Bhoom | Bhor | Bhudargad | Bhusawal | Billoli | Brahmapuri | Buldhana | Butibori | Chalisgaon | Chamorshi | Chandgad | Chandrapur | Chandur | Chanwad | Chhikaldara | Chikhali | Chinchwad | Chiplun | Chopda | Chumur | Dahanu | Dapoli | Darwaha | Daryapur | Daund | Degloor | Delhi Tanda | Deogad | Deolgaonraja | Deori | Desaiganj | Dhadgaon | Dhanora | Dharani | Dhiwadi | Dhule | Dhulia | Digras | Dindori | Edalabad | Erandul | Etapalli | Gadhchiroli | Gadhinglaj | Gaganbavada | Gangakhed | Gangapur | Gevrai | Ghatanji | Golegaon | Gondia | Gondpipri | Goregaon | Guhagar | Hadgaon | Hatkangale | Hinganghat | Hingoli | Hingua | Igatpuri | Indapur | Islampur | Jalgaon | Jalna | Jamkhed | Jamner | Jath | Jawahar | Jintdor | Junnar | Kagal | Kaij | Kalamb | Kalamnuri | Kallam | Kalmeshwar | Kalwan | Kalyan | Kamptee | Kandhar | Kankavali | Kannad | Karad | Karjat | Karmala | Katol | Kavathemankal | Kedgaon | Khadakwasala | Khamgaon | Khed | Khopoli | Khultabad | Kinwat | Kolhapur | Kopargaon | Koregaon | Kudal | Kuhi | Kurkheda | Kusumba | Lakhandur | Langa | Latur | Lonar | Lonavala | Madangad | Madha | Mahabaleshwar | Mahad | Mahagaon | Mahasala | Mahaswad | Malegaon | Malgaon | Malgund | Malkapur | Malsuras | Malwan | Mancher | Mangalwedha | Mangaon | Mangrulpur | Manjalegaon | Manmad | Maregaon | Mehda | Mekhar | Mohadi | Mohol | Mokhada | Morshi | Mouda | Mukhed | Mul | Mumbai | Murbad | Murtizapur | Murud | Nagbhir | Nagpur | Nahavara | Nanded | Nandgaon | Nandnva | Nandurbar | Narkhed | Nashik | Navapur | Ner | Newasa | Nilanga | Niphad | Omerga | Osmanabad | Pachora | Paithan | Palghar | Pali | Pandharkawada | Pandharpur | Panhala | Paranda | Parbhani | Parner | Parola | Parseoni | Partur | Patan | Pathardi | Pathari | Patoda | Pauni | Peint | Pen | Phaltan | Pimpalner | Pirangut | Poladpur | Pune | Pusad | Pusegaon | Radhanagar | Rahuri | Raigad | Rajapur | Rajgurunagar | Rajura | Ralegaon | Ramtek | Ratnagiri | Raver | Risod | Roha | Sakarwadi | Sakoli | Sakri | Salekasa | Samudrapur | Sangamner | Sanganeshwar | Sangli | Sangola | Sanguem | Saoner | Saswad | Satana | Satara | Sawantwadi | Seloo | Shahada | Shahapur | Shahuwadi | Shevgaon | Shirala | Shirol | Shirpur | Shirur | Shirwal | Solapur | Shri Rampur | Shrigonda | Shrivardhan | Sillod | Sinderwahi | Sindhudurg | Sindkheda | Sindkhedaraja | Sinnar | Sironcha | Soyegaon | Surgena | Talasari | Talegaon S.Ji Pant | Taloda | Tasgaon | Thane | Tirora | Tiwasa | Trimbak | Tuljapur | Tumsar | Udgir | Umarkhed | Umrane | Umrer | Urlikanchan | Vaduj | Velhe | Vengurla | Vijapur | Vita | Wada | Wai | Walchandnagar | Wani | Wardha | Warlydwarud | Warora | Washim | Wathar | Yavatmal | Yawal | Yeola | Yeotmal";
						c_a2['Manipur'] = "Bishnupur | Chakpikarong | Chandel | Chattrik | Churachandpur | Imphal | Jiribam | Kakching | Kalapahar | Mao | Mulam | Parbung | Sadarhills | Saibom | Sempang | Senapati | Sochumer | Taloulong | Tamenglong | Thinghat | Thoubal | Ukhrul";
						c_a2['Meghalaya'] = "Amlaren | Baghmara | Cherrapunjee | Dadengiri | Garo Hills | Jaintia Hills | Jowai | Khasi Hills | Khliehriat | Mariang | Mawkyrwat | Nongpoh | Nongstoin | Resubelpara | Ri Bhoi | Shillong | Tura | Williamnagar";
						c_a2['Mizoram'] = "Aizawl | Champhai | Demagiri | Kolasib | Lawngtlai | Lunglei | Mamit | Saiha | Serchhip";
						c_a2['Nagaland'] = "Dimapur | Jalukie | Kiphire | Kohima | Mokokchung | Mon | Phek | Tuensang | Wokha | Zunheboto";
						c_a2['Orissa'] = "Anandapur | Angul | Anugul | Aska | Athgarh | Athmallik | Attabira | Bagdihi | Balangir | Balasore | Baleswar | Baliguda | Balugaon | Banaigarh | Bangiriposi | Barbil | Bargarh | Baripada | Barkot | Basta | Berhampur | Betanati | Bhadrak | Bhanjanagar | Bhawanipatna | Bhubaneswar | Birmaharajpur | Bisam Cuttack | Boriguma | Boudh | Buguda | Chandbali | Chhatrapur | Chhendipada | Cuttack | Daringbadi | Daspalla | Deodgarh | Deogarh | Dhanmandal | Dharamgarh | Dhenkanal | Digapahandi | Dunguripali | G. Udayagiri | Gajapati | Ganjam | Ghatgaon | Gudari | Gunupur | Hemgiri | Hindol | Jagatsinghapur | Jajpur | Jamankira | Jashipur | Jayapatna | Jeypur | Jharigan | Jharsuguda | Jujumura | Kalahandi | Kalimela | Kamakhyanagar | Kandhamal | Kantabhanji | Kantamal | Karanjia | Kashipur | Kendrapara | Kendujhar | Keonjhar | Khalikote | Khordha | Khurda | Komana | Koraput | Kotagarh | Kuchinda | Lahunipara | Laxmipur | M. Rampur | Malkangiri | Mathili | Mayurbhanj | Mohana | Motu | Nabarangapur | Naktideul | Nandapur | Narlaroad | Narsinghpur | Nayagarh | Nimapara | Nowparatan | Nowrangapur | Nuapada | Padampur | Paikamal | Palla Hara | Papadhandi | Parajang | Pardip | Parlakhemundi | Patnagarh | Pattamundai | Phiringia | Phulbani | Puri | Puruna Katak | R. Udayigiri | Rairakhol | Rairangpur | Rajgangpur | Rajkhariar | Rayagada | Rourkela | Sambalpur | Sohela | Sonapur | Soro | Subarnapur | Sunabeda | Sundergarh | Surada | T. Rampur | Talcher | Telkoi | Titlagarh | Tumudibandha | Udala | Umerkote";
						c_a2['Pondicherry'] = "Bahur | Karaikal | Mahe | Pondicherry | Purnankuppam | Valudavur | Villianur | Yanam";
						c_a2['Punjab'] = "Abohar | Ajnala | Amritsar | Balachaur | Barnala | Batala | Bathinda | Chandigarh | Dasua | Dinanagar | Faridkot | Fatehgarh Sahib | Fazilka | Ferozepur | Garhashanker | Goindwal | Gurdaspur | Guruharsahai | Hoshiarpur | Jagraon | Jalandhar | Jugial | Kapurthala | Kharar | Kotkapura | Ludhiana | Malaut | Malerkotla | Mansa | Moga | Muktasar | Nabha | Nakodar | Nangal | Nawanshahar | Nawanshahr | Pathankot | Patiala | Patti | Phagwara | Phillaur | Phulmandi | Quadian | Rajpura | Raman | Rayya | Ropar | Rupnagar | Samana | Samrala | Sangrur | Sardulgarh | Sarhind | SAS Nagar | Sultanpur Lodhi | Sunam | Tanda Urmar | Tarn Taran | Zira";
						c_a2['Rajasthan'] = "Abu Road | Ahore | Ajmer | Aklera | Alwar | Amber | Amet | Anupgarh | Asind | Aspur | Atru | Bagidora | Bali | Bamanwas | Banera | Bansur | Banswara | Baran | Bari | Barisadri | Barmer | Baseri | Bassi | Baswa | Bayana | Beawar | Begun | Behror | Bhadra | Bharatpur | Bhilwara | Bhim | Bhinmal | Bikaner | Bilara | Bundi | Chhabra | Chhipaborad | Chirawa | Chittorgarh | Chohtan | Churu | Dantaramgarh | Dausa | Deedwana | Deeg | Degana | Deogarh | Deoli | Desuri | Dhariawad | Dholpur | Digod | Dudu | Dungarpur | Dungla | Fatehpur | Gangapur | Gangdhar | Gerhi | Ghatol | Girwa | Gogunda | Hanumangarh | Hindaun | Hindoli | Hurda | Jahazpur | Jaipur | Jaisalmer | Jalore | Jhalawar | Jhunjhunu | Jodhpur | Kaman | Kapasan | Karauli | Kekri | Keshoraipatan | Khandar | Kherwara | Khetri | Kishanganj | Kishangarh | Kishangarhbas | Kolayat | Kota | Kotputli | Kotra | Kotri | Kumbalgarh | Kushalgarh | Ladnun | Ladpura | Lalsot | Laxmangarh | Lunkaransar | Mahuwa | Malpura | Malvi | Mandal | Mandalgarh | Mandawar | Mangrol | Marwar-Jn | Merta | Nadbai | Nagaur | Nainwa | Nasirabad | Nathdwara | Nawa | Neem Ka Thana | Newai | Nimbahera | Nohar | Nokha | Onli | Osian | Pachpadara | Pachpahar | Padampur | Pali | Parbatsar | Phagi | Phalodi | Pilani | Pindwara | Pipalda | Pirawa | Pokaran | Pratapgarh | Raipur | Raisinghnagar | Rajgarh | Rajsamand | Ramganj Mandi | Ramgarh | Rashmi | Ratangarh | Reodar | Rupbas | Sadulshahar | Sagwara | Sahabad | Salumber | Sanchore | Sangaria | Sangod | Sapotra | Sarada | Sardarshahar | Sarwar | Sawai Madhopur | Shahapura | Sheo | Sheoganj | Shergarh | Sikar | Sirohi | Siwana | Sojat | Sri Dungargarh | Sri Ganganagar | Sri Karanpur | Sri Madhopur | Sujangarh | Taranagar | Thanaghazi | Tibbi | Tijara | Todaraisingh | Tonk | Udaipur | Udaipurwati | Uniayara | Vallabhnagar | Viratnagar";
						c_a2['Sikkim'] = "Barmiak | Be | Bhurtuk | Chhubakha | Chidam | Chubha | Chumikteng | Dentam | Dikchu | Dzongri | Gangtok | Gauzing | Gyalshing | Hema | Kerung | Lachen | Lachung | Lema | Lingtam | Lungthu | Mangan | Namchi | Namthang | Nanga | Nantang | Naya Bazar | Padamachen | Pakhyong | Pemayangtse | Phensang | Rangli | Rinchingpong | Sakyong | Samdong | Singtam | Siniolchu | Sombari | Soreng | Sosing | Tekhug | Temi | Tsetang | Tsomgo | Tumlong | Yangang | Yumtang";
						c_a2['Tamil Nadu'] = "Ambasamudram | Anamali | Arakandanallur | Arantangi | Aravakurichi | Ariyalur | Arkonam | Arni | Aruppukottai | Attur | Avanashi | Batlagundu | Bhavani | Chengalpattu | Chengam | Chennai | Chidambaram | Chingleput | Coimbatore | Courtallam | Cuddalore | Cumbum | Denkanikoitah | Devakottai | Dharampuram | Dharmapuri | Dindigul | Erode | Gingee | Gobichettipalayam | Gudalur | Gudiyatham | Harur | Hosur | Jayamkondan | Kallkurichi | Kanchipuram | Kangayam | Kanyakumari | Karaikal | Karaikudi | Karur | Keeranur | Kodaikanal | Kodumudi | Kotagiri | Kovilpatti | Krishnagiri | Kulithalai | Kumbakonam | Kuzhithurai | Madurai | Madurantgam | Manamadurai | Manaparai | Mannargudi | Mayiladuthurai | Mayiladutjurai | Mettupalayam | Metturdam | Mudukulathur | Mulanur | Musiri | Nagapattinam | Nagarcoil | Namakkal | Nanguneri | Natham | Neyveli | Nilgiris | Oddanchatram | Omalpur | Ootacamund | Ooty | Orathanad | Palacode | Palani | Palladum | Papanasam | Paramakudi | Pattukottai | Perambalur | Perundurai | Pollachi | Polur | Pondicherry | Ponnamaravathi | Ponneri | Pudukkottai | Rajapalayam | Ramanathapuram | Rameshwaram | Ranipet | Rasipuram | Salem | Sankagiri | Sankaran | Sathiyamangalam | Sivaganga | Sivakasi | Sriperumpudur | Srivaikundam | Tenkasi | Thanjavur | Theni | Thirumanglam | Thiruraipoondi | Thoothukudi | Thuraiyure | Tindivanam | Tiruchendur | Tiruchengode | Tiruchirappalli | Tirunelvelli | Tirupathur | Tirupur | Tiruttani | Tiruvallur | Tiruvannamalai | Tiruvarur | Tiruvellore | Tiruvettipuram | Trichy | Tuticorin | Udumalpet | Ulundurpet | Usiliampatti | Uthangarai | Valapady | Valliyoor | Vaniyambadi | Vedasandur | Vellore | Velur | Vilathikulam | Villupuram | Virudhachalam | Virudhunagar | Wandiwash | Yercaud";
						c_a2['Tripura'] = "Agartala | Ambasa | Bampurbari | Belonia | Dhalai | Dharam Nagar | Kailashahar | Kamal Krishnabari | Khopaiyapara | Khowai | Phuldungsei | Radha Kishore Pur | Tripura";
						c_a2['Uttar Pradesh'] = "Achhnera | Agra | Akbarpur | Aliganj | Aligarh | Allahabad | Ambedkar Nagar | Amethi | Amiliya | Amroha | Anola | Atrauli | Auraiya | Azamgarh | Baberu | Badaun | Baghpat | Bagpat | Baheri | Bahraich | Ballia | Balrampur | Banda | Bansdeeh | Bansgaon | Bansi | Barabanki | Bareilly | Basti | Bhadohi | Bharthana | Bharwari | Bhogaon | Bhognipur | Bidhuna | Bijnore | Bikapur | Bilari | Bilgram | Bilhaur | Bindki | Bisalpur | Bisauli | Biswan | Budaun | Budhana | Bulandshahar | Bulandshahr | Capianganj | Chakia | Chandauli | Charkhari | Chhata | Chhibramau | Chirgaon | Chitrakoot | Chunur | Dadri | Dalmau | Dataganj | Debai | Deoband | Deoria | Derapur | Dhampur | Domariyaganj | Dudhi | Etah | Etawah | Faizabad | Farrukhabad | Fatehpur | Firozabad | Garauth | Garhmukteshwar | Gautam Buddha Nagar | Ghatampur | Ghaziabad | Ghazipur | Ghosi | Gonda | Gorakhpur | Gunnaur | Haidergarh | Hamirpur | Hapur | Hardoi | Harraiya | Hasanganj | Hasanpur | Hathras | Jalalabad | Jalaun | Jalesar | Jansath | Jarar | Jasrana | Jaunpur | Jhansi | Jyotiba Phule Nagar | Kadipur | Kaimganj | Kairana | Kaisarganj | Kalpi | Kannauj | Kanpur | Karchhana | Karhal | Karvi | Kasganj | Kaushambi | Kerakat | Khaga | Khair | Khalilabad | Kheri | Konch | Kumaon | Kunda | Kushinagar | Lalganj | Lalitpur | Lucknow | Machlishahar | Maharajganj | Mahoba | Mainpuri | Malihabad | Mariyahu | Math | Mathura | Mau | Maudaha | Maunathbhanjan | Mauranipur | Mawana | Meerut | Mehraun | Meja | Mirzapur | Misrikh | Modinagar | Mohamdabad | Mohamdi | Moradabad | Musafirkhana | Muzaffarnagar | Nagina | Najibabad | Nakur | Nanpara | Naraini | Naugarh | Nawabganj | Nighasan | Noida | Orai | Padrauna | Pahasu | Patti | Pharenda | Phoolpur | Phulpur | Pilibhit | Pitamberpur | Powayan | Pratapgarh | Puranpur | Purwa | Raibareli | Rampur | Ramsanehi Ghat | Rasara | Rath | Robertsganj | Sadabad | Safipur | Sagri | Saharanpur | Sahaswan | Sahjahanpur | Saidpur | Salempur | Salon | Sambhal | Sandila | Sant Kabir Nagar | Sant Ravidas Nagar | Sardhana | Shahabad | Shahganj | Shahjahanpur | Shikohabad | Shravasti | Siddharthnagar | Sidhauli | Sikandra Rao | Sikandrabad | Sitapur | Siyana | Sonbhadra | Soraon | Sultanpur | Tanda | Tarabganj | Tilhar | Unnao | Utraula | Varanasi | Zamania";
						c_a2['Uttaranchal'] = "Almora | Bageshwar | Bhatwari | Chakrata | Chamoli | Champawat | Dehradun | Deoprayag | Dharchula | Dunda | Haldwani | Haridwar | Joshimath | Karan Prayag | Kashipur | Khatima | Kichha | Lansdown | Munsiari | Mussoorie | Nainital | Pantnagar | Partapnagar | Pauri Garhwal | Pithoragarh | Purola | Rajgarh | Ranikhet | Roorkee | Rudraprayag | Tehri Garhwal | Udham Singh Nagar | Ukhimath | Uttarkashi";
						c_a2['West Bengal'] = "Adra | Alipurduar | Amlagora | Arambagh | Asansol | Balurghat | Bankura | Bardhaman | Basirhat | Berhampur | Bethuadahari | Birbhum | Birpara | Bishanpur | Bolpur | Bongoan | Bulbulchandi | Burdwan | Calcutta | Canning | Champadanga | Contai | Cooch Behar | Daimond Harbour | Dalkhola | Dantan | Darjeeling | Dhaniakhali | Dhuliyan | Dinajpur | Dinhata | Durgapur | Gangajalghati | Gangarampur | Ghatal | Guskara | Habra | Haldia | Harirampur | Harishchandrapur | Hooghly | Howrah | Islampur | Jagatballavpur | Jalpaiguri | Jhalda | Jhargram | Kakdwip | Kalchini | Kalimpong | Kalna | Kandi | Karimpur | Katwa | Kharagpur | Khatra | Krishnanagar | Mal Bazar | Malda | Manbazar | Mathabhanga | Medinipur | Mekhliganj | Mirzapur | Murshidabad | Nadia | Nagarakata | Nalhati | Nayagarh | Parganas | Purulia | Raiganj | Rampur Hat | Ranaghat | Seharabazar | Siliguri | Suri | Takipur | Tamluk";

						$('#country2').change(function() {
							var c2 = $(this).val();
							var state_arr2 = s_a2[c2].split("|");
							$('#state2').empty();
							$('#city2').empty();
							if (c2 == 0) {
								$('#state2').append($('<option>', {
									value : '0',
									text : 'Select State',
								}, '</option>'));
							} else {
								$.each(state_arr2, function(m, item_state) {
									$('#state2').append($('<option>', {
										value : item_state,
										text : item_state,
									}, '</option>'));
								});
							}
							$('#city2').append($('<option>', {
								value : '0',
								text : 'Select City',
							}, '</option>'));
						});

						$('#state2').change(function() {
							var s2 = $(this).val();
							if (s2 == 'Select State') {
								$('#city2').empty();
								$('#city2').append($('<option>', {
									value : '0',
									text : 'Select City',
								}, '</option>'));
							}
							var city_arr2 = c_a2[s2].split("|");
							$('#city2').empty();

							$.each(city_arr2, function(n, item_city) {

								$('#city2').append($('<option>', {
									value : item_city,
									text : item_city,
								}, '</option>'));
							});
							//
							//<select name="chapter" id="chapter">
							//    <option value="" selected="selected">Please select topic first</option>
							//  </select>
						});
					});
</script>
<style>
#add_user{
}</style>

</head>

<body>

        
	<%@include file="header.html"%>
	<button class="back" onclick="history.back()">Back</button>

	<br>
	<div class="container col-md-7">
		<div class="card">
			<div class="card-body">
				<c:if test="${user != null}">
					<form action="update" method="post" enctype="multipart/form-data" multiple=webkitdirectory=''>
				</c:if>
				<c:if test="${user == null}">
					<form action="insert" method="post" enctype="multipart/form-data">
				</c:if>
				<caption>
					<h2>
						<c:if test="${user != null}">
                                    Edit User
                                </c:if>
						<c:if test="${user == null}">
                                    Add New User
                                </c:if>
					</h2>
				</caption>
				<c:if test="${user != null}">
					<input type="hidden" name="id" value="<c:out value='${user.id}' />" />
				</c:if>


<table><tr><td>


				<fieldset>
					<label>Industry</label><br/> <select name="industry1" id="industry1"
						 onchange="SelectedTextValue4(this)" class="form-control">

						<option selected="selected" hidden></option>

					</select> <input type="text" id="txtcontent10" name="txtcontent10"
						value="<c:out value='${user.industry}' />" class="form-control"/>
				</fieldset></td>
				<td><fieldset >
					<label>CATEGORY</label><br/> <select name="category1" id="category1"
						onchange="SelectedTextValue7(this)"  class="form-control">
						<option selected="selected"></option>
					</select> <input type="text" id="txtcontent11" name="txtcontent11"
						value="<c:out value='${user.category}' />" class="form-control" />
				<fieldset></td>
				<td><fieldset class="form-group">
					<label>SUB-CATEGORY</label> <select name="sub_category1"
						id="sub_category1" onchange="SelectedTextValue6(this)"
						class="form-control">
						<option selected="selected" value=""></option>


					</select> <input type="text" id="txtcontent12" name="txtcontent12"
						value="<c:out value='${user.sub_category}' />" class="form-control" />
				</fieldset></td></tr>


				<tr><td><fieldset class="form-group">
					<label>COUNTRY</label> <select name="country2" id="country2"
						class="form-control" onchange="SelectedTextValue13(this)">

						<option selected="selected" value=""></option>

					</select> <input type="text" id="txtcontent13" name="txtcontent13"
						value="<c:out value='${user.country}' />" />
				</fieldset></td>
				<td><fieldset class="form-group">
					<label>STATE</label> <select name="state2" id="state2"
						onchange="SelectedTextValue14(this)" class="form-control">
						<option selected="selected" value=""></option>
					</select> <input type="text" id="txtcontent14" name="txtcontent14"
						value="<c:out value='${user.state}' />" />
				</fieldset></td>
				<td><fieldset class="form-group">
					<label>CITY</label> <select name="city2" id="city2"
						onchange="SelectedTextValue15(this)" class="form-control">

						<option selected="selected" value=""></option>


					</select> <input type="text" id="txtcontent15" name="txtcontent15"
						value="<c:out value='${user.city}' />" />
				</fieldset></td></tr>
				<tr><td><fieldset class="form-group">
					<label>COMPANY_NAME</label> <input type="text"
						value="<c:out value='${user.company_name}' />"
						class="form-control" id="company_name" name="company_name">
				</fieldset></td>
				<td><fieldset class="form-group">
					<label>ADDRESS</label> <input type="text"
						value="<c:out value='${user.address}' />" class="form-control"
						id="address" name="address">
				</fieldset></td>

				<td><fieldset class="form-group">
					<label>PIN</label> <input type="text"
						value="<c:out value='${user.pin}' />" class="form-control"
						id="pin" name="pin">
				</fieldset></td></tr>


				<tr><td><fieldset class="form-group">
					<label>CONTACT_PERSON</label> <input type="text"
						value="<c:out value='${user.contact_person}' />"
						class="form-control" id="contact_person" name="contact_person">
				</fieldset></td>
				<td><fieldset class="form-group">
					<label>EMAIL</label> <input type="email"
						value="<c:out value='${user.email}' />" class="form-control"
						name="email">
				</fieldset></td>

				<td><fieldset class="form-group">
					<label>CONTACT NUMBER</label> <input type="text"
						value="<c:out value='${user.contact_number}' />"
						class="form-control"  id="contact_number"name="contact_number">
				</fieldset></td></tr>

				<tr><td><fieldset class="form-group">
					<label>LANDLINE</label> <input type="text"
						value="<c:out value='${user.landline}' />" class="form-control"
						id="landline" name="landline">
				</fieldset></td>

				<td><fieldset class="form-group">
					<label>GST NUMBER</label> <input type="text"
						value="<c:out value='${user.gst_number}' />" class="form-control"
						id="gst_number" name="gst_number">
				</fieldset></td>
				<td><fieldset class="form-group">
					<label>WEB-SITE</label> <input type="text"
						value="<c:out value='${user.web_site}' />" class="form-control"
						id="web_site" name="web_site">
				</fieldset></td></tr>
				<tr><td><fieldset class="form-group">
					<label>TYPE OF BUSINESS</label> <input type="text"
						value="<c:out value='${user.type_of_business}' />"
						class="form-control" id="type_of_business" name="type_of_business">
				</fieldset></td>


				<td><fieldset class="form-group">
					<label>PRODUCT CATALOGUE</label> <input type="file"
						value="<c:out value='${user.product_catalouge}' />"
						class="form-control" id="product_catalouge" name="product_catalouge"  accept=".png, .gif, .jpeg, .jpg" enctype='application/x-www-form-urlencoded' multiple=webkitdirectory=''>
				</fieldset></td></tr>
				


				<tr><td><button type="save" name="button" value="button" 
					class="btn btn-success">Save</button></td></tr></table>


				</form>
			</div>
		</div>
	</div>

	<script>
		function SelectedTextValue4(ele) {
			if (ele.selectedIndex > 0) {
				var selectedText = ele.options[ele.selectedIndex].innerHTML;
				var selectedValue = ele.value;
				document.getElementById("txtcontent10").value = selectedText;

			} else {
				document.getElementById("txtcontent10").value = "";
			}
		}
		function SelectedTextValue7(ele) {
			if (ele.selectedIndex > 0) {
				var selectedText = ele.options[ele.selectedIndex].innerHTML;
				var selectedValue = ele.value;
				document.getElementById("txtcontent11").value = selectedText;
			} else {
				document.getElementById("txtcontent11").value = "";
			}
		}
		function SelectedTextValue6(ele) {
			if (ele.selectedIndex > 0) {
				var selectedText = ele.options[ele.selectedIndex].innerHTML;
				var selectedValue = ele.value;
				document.getElementById("txtcontent12").value = selectedText;
			} else {
				document.getElementById("txtcontent12").value = "";
			}
		}
		function SelectedTextValue13(ele) {
			if (ele.selectedIndex > 0) {
				var selectedText = ele.options[ele.selectedIndex].innerHTML;
				var selectedValue = ele.value;
				document.getElementById("txtcontent13").value = selectedText;
			} else {
				document.getElementById("txtcontent13").value = "";
			}
		}
		function SelectedTextValue14(ele) {
			if (ele.selectedIndex > 0) {
				var selectedText = ele.options[ele.selectedIndex].innerHTML;
				var selectedValue = ele.value;
				document.getElementById("txtcontent14").value = selectedText;
			} else {
				document.getElementById("txtcontent14").value = "";
			}
		}
		function SelectedTextValue15(ele) {
			if (ele.selectedIndex > 0) {
				var selectedText = ele.options[ele.selectedIndex].innerHTML;
				var selectedValue = ele.value;
				document.getElementById("txtcontent15").value = selectedText;
			} else {
				document.getElementById("txtcontent15").value = "";
			}
		}
	</script>


	<%@include file="footer.html"%>
</body>

</html>
